### ISSUE TITLE
Running using es5 configuration gives error on command line with browserify

### ISSUE THREAD

**Issue by jwir3** [bubkoo/html-to-image#1]
**Steps to Reproduce**:

1. Add the following to the source file being run:
```
var htmlToImage = require('html-to-image');
var svgNode = document.getElementById('someIdOfSvgElement');
htmlToImage.toPng(svgNode)
    .then(function (dataUrl) {
      console.log(dataUrl);
    })
    .catch(function (error) {
      console.error('Unable to capture SVG node with id: "' + aSvgId + '"');
    });
```
2. Run using browserify (command in package.json):
```
"scripts": {
    "captureImage": "browserify captureImage.js -o bundle.js && open run.html"
}
```

Note that `run.html` in this case includes the `bundle.js` script.

**Expected Results**: 
  * ✅ Browserify completes successfully, launches the `run.html` page.

**Actual Results**:
  * ❌ The following error is given on the command line:
```
import cloneNode from './cloneNode';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

My thinking is that this has something to do with how browserify isn't using es2015 or es2016. I did try using `babelify`, as in the following example:

```
"scripts": {
    "captureImage": "browserify captureImage.js -o bundle.js -t [ babelify --presets [ env ] ] && open run.html"
}
```

(After installing `babelify, babel-core, and babel-preset-env`, of course)

This seems to result in the same error.

**Comment by sylviestephanies** [comment]
yes i got the same error, can someone help me?

**Comment by edsmcosta** [comment]
Me too, i've got this output:

/media/edsmc/Dados/VALE/passportRAC/node_modules/html-to-image/lib/index.js:1
(function (exports, require, module, __filename, __dirname) { import cloneNode from './cloneNode';
                                                                     ^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
