### ISSUE TITLE
Unable to capture 'screenshot' of Google map

### ISSUE THREAD

**Issue by roguebug** [bubkoo/html-to-image#116]
First of all, great work. This is the easiest to use and WORKING module.

I tried to save Google map as an image. The generated image is not exactly the same. In some case, it is very different.

### Expected Behavior
The image should look the same as the google map

### Current Behavior
See attached screenshots. The left is a Google map using agm-map. The right is generated data PNG. In picture 1, the generated image is very different. In picture 2, only part of the Google map is in the PNG.  

![html-to-image-googlemap - 1](https://user-images.githubusercontent.com/26971609/115099465-a361af00-9efb-11eb-8a65-51847bab1e8d.png)
![html-to-image-googlemap - 2](https://user-images.githubusercontent.com/26971609/115099463-a361af00-9efb-11eb-8d9f-8cfb208bb384.png)

My code is nothing fancy:
htmlToImage.toPng(element).then((dataUrl) => {
      that.imageData = dataUrl;
    }).catch(function (error) {
      console.error('oops, something went wrong!', error);
    });

I noticed the error message in the console:
Error while reading CSS rules from https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Google+Sans:400,500,700 SecurityError: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules

Not sure if this is what screws up the image rendering.

### Your Environment

- html-to-image: 1.6.0
- OS: Windows 10
- Browser: 89.0.4389.128 (Official Build) (64-bit)
- Angular: 8
"dependencies": {
    "@agm/core": "^3.0.0-beta.0",
    "@angular/animations": "~8.2.14",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@types/googlemaps": "^3.39.8",
    "dom-to-image": "^2.6.0",
    "html-to-image": "^1.6.0",
    "html2canvas": "^1.0.0-rc.7",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  }

**Comment by maxizhukov** [comment]
I also have same issue, Why are you closing without fixing?

**Comment by managervcf** [comment]
I managed to solve this issue with the `html2canvas` library.
Addind the `{ useCORS: true }` option made it magically it work for me.

If anyone needs, I'm sharing my custom React hook below:
```
import html2canvas from 'html2canvas';
import { MutableRefObject } from 'react';

/**
 * A hook that exports a function allowing to capture a specific HTMLElement as an image.
 */
export function useScreenshot<T extends HTMLElement>(ref: MutableRefObject<T | null>, filename: string) {
  const takeScreenShot = async (node: T | null) => {
    if (!node) {
      return;
    }

    const dataURI = await html2canvas(
      node,
      // This is a very important line as it allows to capture an image of Google Maps!
      { useCORS: true },
    );
    return dataURI;
  };

  const download = (canvas?: HTMLCanvasElement) => {
    const a = document.createElement('a');

    a.target = '_blank';
    a.href = canvas?.toDataURL() ?? '';
    a.download = `${filename}.jpeg`;
    a.click();
  };

  const downloadScreenshot = () => takeScreenShot(ref.current).then(download);

  return { downloadScreenshot };
}
```
