### ISSUE TITLE
Can you provide an example using React?

### ISSUE THREAD

**Issue by chriswalz-bg** [bubkoo/html-to-image#122]
I'm not sure how to get it working without using findDomNode in conjunction with RootRef

**Comment by hdoro** [comment]
Hey Chris 👋

Maybe this snippet can give you a north?

Here's what a `useScreenshot` hook could look like:
```tsx
import download from 'downloadjs'
import { toPng } from 'html-to-image'
import React from 'react'

/**
 * Hook to generate screenshot
 */
function useScreenshot() {
  const captureRef = React.useRef()

  const [status, setStatus] = React.useState('idle')

  async function generateImage(e) {
    e.preventDefault()
    if (!captureRef?.current) {
      return
    }
    try {
      setStatus('loading')
      const imgBase64 = await toPng(captureRef.current, {
        quality: 1,
        pixelRatio: 1,
      })
      setStatus('success')
      download(imgBase64, 'generated.png')
    } catch (error) {
      setStatus('error')
      console.error(error)
    }
  }

  return {
    generateImage,
    captureRef,
    status,
  }
}

export default useScreenshot
```

And how a component could consume it:
```tsx
import React from "react";
import useScreenshot from "./useScreenshot";

const MyComponent = () => {
  const { generateImage, captureRef, status } = useScreenshot();
  return (
    <>
      <div ref={captureRef}>
        <h1>I'll become an image!!</h1>
      </div>
      <button disabled={status === "loading"} onClick={generateImage}>
        Generate image
      </button>
    </>
  );
};

export default MyComponent;
```

**Comment by Vordty** [comment]
@hdoro

 Hey, thanks for the example.
 I came across an issue while using your code.
 **toPng** does not seem to work for specific refs such as the button in the example, but works fine if I just pass "document.body" to it.
 By not work I mean - function returns base64 but image is empty, it took a screenshot of nothing.
 
 Do you have any clue what could be the issue?
 Thanks for help.

**Comment by Vordty** [comment]
If anyone's wondering I fixed it.

Just wrap another container/div around the element you want to capture and attach ref to that outer container.
I think this was intended in the example above, my bad.

**Comment by ndisisnd** [comment]
Absolutely amazing. That helped me a lot as well—any chance of creating an integration guide for different frameworks?

**Comment by mgw-sbex** [comment]
Hi All, Hoping to get this great lib to work. I have a probably silly question... I'm importing into my container like this:
import htmlToImage from 'html-to-image';
import { toPng, toJpeg, toBlob, toPixelData, toSvg } from 'html-to-image';

I'm invoking it like this:
capture = (id) => {
    htmlToImage.toPng(document.getElementById(id))
    .then(function (dataUrl) {
      var img = new Image();
      img.src = dataURL;
      document.body.appendChild(img);
      saveImgAs(dataUrl, 'my-node.png');
    })
    .catch(function (error) {
      console.error('capture error', error);
    });
  };

and the button to fire it is like this:
  <button id="snap" className="snapfs"  onClick={this.capture.bind(this,'upper-container')} allow="fullscreen"></button>
            
When I click the button I get:
react-dom.production.min.js?ca5d:21 Uncaught TypeError: Cannot read property 'toPng' of undefined
    at ConferencePage.eval [as capture] (index.js?2994:1175)<-- where I called htmlToImage above
    at Object.ca (react-dom.production.min.js?ca5d:14)
    at ja (react-dom.production.min.js?ca5d:15)
    at ka (react-dom.production.min.js?ca5d:15)
    at wa (react-dom.production.min.js?ca5d:17)
    at Aa (react-dom.production.min.js?ca5d:18)
    at ya (react-dom.production.min.js?ca5d:18)
    at Da (react-dom.production.min.js?ca5d:21)
    at Ad (react-dom.production.min.js?ca5d:84)
    at Gi (react-dom.production.min.js?ca5d:250)

Any idea what I'm doing wrong when importing?
