### ISSUE TITLE
@font-face not included in SVGs

### ISSUE THREAD

**Issue by junkdeck** [bubkoo/html-to-image#13]
I'm currently attempting to render out some SVG graphs to JPEG. It works fine after inlining all styles, as there were some "insecure operation" warnings when trying to read from CSS, but one thing I just cannot get working is using web fonts in SVG.

I've tried both importing the fonts using `@import` from Google Fonts, and defining the font with `@font-face`.

I tried putting `fontFamily: 'Roboto'` in the `style` object of options, as well as inlining `style={{fontFamily: 'Roboto'}}` directly on a `<text>` SVG element, neither worked.

Probably worth mentioning I'm using React for this.
I'm kinda running out of ideas. Any help?

**Comment by junkdeck** [comment]
Found a workaround for this, posting in case anyone else has the same issue.

```
const node = document.getElementById('chart-container')
node.querySelectorAll('text').forEach( tag => tag.style.fontFamily = "Roboto, Arial, Sans Serif")
```

**Comment by Avishaidev** [comment]
> Found a workaround for this, posting in case anyone else has the same issue.
> 
> ```
> const node = document.getElementById('chart-container')
> node.querySelectorAll('text').forEach( tag => 
>   (tag.style.fontFamily = "Roboto, Arial, Sans Serif")
> )
> ```

Where did you write this code?
My issue is with ionic 3 icons that are not rendered as icon

**Comment by junkdeck** [comment]
I manipulate nodes in a `buildImage` function where I pass the `node` to be rendered. I don't think it'll help in your case, though.

**Comment by Abdullah0991** [comment]
I have the same issue with Angular Material 7, I use html-to-image to capture an image of ngx-charts.
I tried @junkdeck solution but it doesn't give me a better results.

In original library dom-to-image, this problem is not exists, @bubkoo could you please fix this issue?
