### ISSUE TITLE
FontAwesome icons are not displayed on Safari

### ISSUE THREAD

**Issue by runkow** [bubkoo/html-to-image#130]
### Expected Behavior

FontAwesome icons should be rendered in the resulting image.

### Current Behavior

FontAwesome icons are not rendered in the resulting image.

### Your Environment

- html-to-image: 1.6.1
- OS: macOS Big Sur 11.3.1
- Browser: safari 14.1

**Comment by runkow** [comment]
keep it open

**Comment by runkow** [comment]
> Hiya!
> This issue has gone quiet. Spooky quiet. 👻
> We get a lot of issues, so we currently close issues after 60 days of inactivity. It’s been at least 20 days since the last update here. If we missed this issue or if you want to keep it open, please reply here. You can also add the label "not-stale" to keep this issue open! As a friendly reminder: the best way to see this issue, or any other, fixed is to open a Pull Request.
> 
> Thanks for being a part of the Antv community! 💪💯

keep it open

**Comment by sm3sher** [comment]
> Hiya!
> This issue has gone quiet. Spooky quiet. 👻
> We get a lot of issues, so we currently close issues after 60 days of inactivity. It’s been at least 20 days since the last update here. If we missed this issue or if you want to keep it open, please reply here. You can also add the label "not-stale" to keep this issue open! As a friendly reminder: the best way to see this issue, or any other, fixed is to open a Pull Request.
> 
> Thanks for being a part of the Antv community! 💪💯

still an issue
