### ISSUE TITLE
feature: Support shadow dom (not-stale)

### ISSUE THREAD

**Issue by Yohandah** [bubkoo/html-to-image#135]
As requested here before : https://github.com/bubkoo/html-to-image/issues/24

Shadow dom support would be nice. Ionic uses a lot of shadow dom in its components

**Comment by ShaMan123** [comment]
#129

**Comment by Yohandah** [comment]
@ShaMan123 It doesn't work with shadow dom from Ionic 

* Add a ionic component (whatever the component)
* target it and use html-to-image to get the image
* the image is blank

https://stackblitz.com/edit/html-to-image-shadow?file=src/app/app.component.ts
(stackblitz doesn't work with html-to-image but you can clone it and run it locally)

**Comment by ShaMan123** [comment]
Look here:
https://github.com/tsayen/dom-to-image/pull/370/files#diff-f6f870a0431c843167c23a771cd968e766fe3eea5cad9cf36307337620bcfb76R250

I didn't add `:first-line` to the pseudo elements. You only need that I think

**Comment by ShaMan123** [comment]
You simply need to find the place where the pseudo elements are defined

**Comment by ShaMan123** [comment]
https://github.com/bubkoo/html-to-image/blob/master/src/clonePseudoElements.ts#L7
https://github.com/bubkoo/html-to-image/blob/master/src/clonePseudoElements.ts#L14

**Comment by Yohandah** [comment]
not-stale

**Comment by Serjobas** [comment]
upvote

**Comment by Yohandah** [comment]
not-stale

**Comment by techquestions** [comment]
not-stale

**Comment by techquestions** [comment]
not stale

**Comment by Yohandah** [comment]
🤦🏻‍♂️

**Comment by Yohandah** [comment]
🙄

**Comment by hynekpetrla** [comment]
not-stale

**Comment by hynekpetrla** [comment]
🙄

**Comment by hynekpetrla** [comment]
🙋‍♂️
