### ISSUE TITLE
youtube embedded videos shows as blank images

### ISSUE THREAD

**Issue by alvacoder** [bubkoo/html-to-image#139]
### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- html-to-image: [e.g. 0.1.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by yuis-ice** [comment]
I have the same issue.
