### ISSUE TITLE
Why reinvent the wheel when there is canvas-to-buffer?

### ISSUE THREAD

**Issue by binarykitchen** [bubkoo/html-to-image#14]
Hi there

I was very curious to check code of your package and realise parts already exist in this package
https://github.com/binarykitchen/canvas-to-buffer

So probably don't want to reinvent the wheel?

**Comment by stephencorwin** [comment]
![image](https://user-images.githubusercontent.com/3931162/61757004-ba0dbd00-ad8c-11e9-84c6-7e654ff09c61.png)

shameless plug much? you just linked to your own crappy library that is unused by anyone. How about you archive your library and direct people here instead.

**Comment by binarykitchen** [comment]
Ha! No offence, only want the best for everyone. As I said https://github.com/binarykitchen/canvas-to-buffer only does a little part of your whole package. Larger packages should be built with smaller packages as if these were like Lego, a fundamental software engineering principle.

Your html-to-image package has nice, convenient functions for generating images by given format and more. This is what most developers are after, not a buffer like my package does. Hence, more stars/popularity.

**Comment by stephencorwin** [comment]
it isn't my package, i'm just a passersby looking at potentially using this package. I just didn't like how you very obviously advertising your own competing package.

**Comment by binarykitchen** [comment]
Oh ok. Nope, not my intention to advertise my package. Only care about a healthier npm ecosystem instead of too many fragmented Lego pieces. If there is a better package out there than mine which does exactly the same one thing, then I'm willing to switch to it.

**Comment by herrbasan** [comment]
The problem with the whole open source eco system is that it initially depends on advertising your lib. If no one knows it, no one will use it. So the popularity contest that is the mechanism to sort out the good from the bad doesn't even happen. So it is possible that his lib is the neater more robust way of doing it, but without anyone knowing, it won't get adopted. The only solution is to poke people to consider the library.

**Comment by binarykitchen** [comment]
Right, good points. Especially re: advertising and popularity contest. And quoting you: 

> The only solution is to poke people to consider the library.

Isn't that what I am doing, poking here to consider using the other library? :)

**Comment by herrbasan** [comment]
That was the point, I defended you doing so.
