### ISSUE TITLE
Adding in script tag?

### ISSUE THREAD

**Issue by elifsz** [bubkoo/html-to-image#145]
How can I add as a script tag?

**Comment by Fish1** [comment]
I would also like to simply add a script tag. I am not using modules in my project.

**Comment by Fish1** [comment]
I was looking at that package. I'm not sure how to get it working because the JS uses ES modules. I ended up using https://www.jsdelivr.com/package/npm/dom-to-image because it doesn't use modules.

I would really like to use html-to-image

**Comment by egfx** [comment]
I thought wzrd.in could have worked out but it’s service is down. Anybody know an alternative?

**Comment by mvinoba** [comment]
Any updates on this from someone who understands JS better than I do?

**Comment by egfx** [comment]
I too ended up using dom2image as this package was impossible to get working via a script tag.

**Comment by layinka** [comment]
Thats the thing with recent packages deployed to npm.

Using a library like this in the past will have just required adding them to a script tag a few years back, now we cant use this unless you are using modules etc

I also ended up going back to dom2image

**Comment by egfx** [comment]
It’s sometimes possible to get NPM modules working via a script tag use unpkg.com but that doesn’t work here unfortunately.

**Comment by mvinoba** [comment]
@egfx I could make it work adding `<script src="https://unpkg.com/html-to-image@1.7.0/dist/html-to-image.js"></script>` to my code.

**Comment by egfx** [comment]
> @egfx I made it work by adding `<script src="https://unpkg.com/html-to-image@1.7.0/dist/html-to-image.js"></script>` to my code.

This doesn't work in my case because I need all URL's to point to a base url I define and I can't define unpkg.com as the base url. It may work if your using this library as is.
