### ISSUE TITLE
Safari Doesn't display images from URL (CORS enabled) - no error thrown

### ISSUE THREAD

**Issue by bardiaheshmati** [bubkoo/html-to-image#147]
Images loaded from URL is not being rendered in safari, chrome has no issues

### Expected Behavior

To display images that are provided by url

### Current Behavior

Renders a placeholder in size of the original photo but brings empty

### Steps To Reproduce

- Load any Image from external resource and place in the element and generate image from HTML, no error is thrown. CORS is also enabled

### Your Environment

- html-to-image: 1.6.2
- OS:  Mac OS Big Sur (11.2.3) 
- React - NextJs
- Browser: Safari  14.0.3

**Comment by valtism** [comment]
I have this too, but the funny thing is that it only happens on the first try. When I run it a second time, the images are produced correctly. I wonder if it is a thing where Safari is not allowing time for the images to download.

**Comment by bardiaheshmati** [comment]
yes i noticed that too. i don't know if fetching photos are asynchronous or there is something blocking the first view, i noticed a flash like reloading of the photo when i scroll up and down, and exactly after that flash, the photos render again.

**Comment by valtism** [comment]
This might be an unhelpful comment, but after having edge case after edge case breaking across multiple libraries, I solved my problem by doing the canvas manipulation by hand. My use-case was not overly complicated and working with the canvas directly turned out to not be as scary as I though. If you have a simple enough use-case you might want to consider doing this.

**Comment by bardiaheshmati** [comment]
i tried, converting to canvas to SVG in a hope that it will turn the photo to a base64 and then to jpeg. it doesn't really work.

**Comment by pouu69** [comment]
i have same issue.
how can i use it?

**Comment by Blackfaded** [comment]
Having the same issue.

**Comment by yumemi-omi** [comment]
I faced the same issue. Please give me a workaround.

**Comment by yumemi-omi** [comment]
My workaround is doing html-to-image twice.

```
const convertHtml2Image = async (element, isSafari) => {
  if (isSafari) {
    await toPng(element, { cacheBust: true })
  }
  await toPng(element, { cacheBust: true, }).then((dataUrl) => {
    const link = document.createElement('a')
    link.download = 'my-image-name.png'
    link.href = dataUrl
    link.click()
  })
}
```

**Comment by hansanwok** [comment]
For me, twice sometimes is nto enough, I loop util it been as expected
let imgBase64

      imgBase64 = await toPng(captureRef.current, options)

      while (isSafari && imgBase64.length < 100000) {
        imgBase64 = await toPng(captureRef.current, options)
      }
