### ISSUE TITLE
toPng in React only captures static JSX within my component and not content rendered by child components?

### ISSUE THREAD

**Issue by sudwald** [bubkoo/html-to-image#153]
I'm running htmlToImage within a React component. Within the div which I am turning into an image, I have some content rendered by static JSX (e.g. headers) and some dynamic content rendered by child components. 

I've tried it in a few test contexts and in each case it only renders the static JSX on the page, not anything which my child components are rendering. Is this a limitation of the package or am I doing something wrong / is there a work-around?

**Comment by hexdecimal16** [comment]
how did you solved it?
