### ISSUE TITLE
ToJpeg method generates a full black picture

### ISSUE THREAD

**Issue by MonalisaBaltatescu** [bubkoo/html-to-image#155]
### Expected Behavior

ToJpeg method should generate a jpeg format image out of HTML content.

### Current Behavior

The image is created but it is all black

![image](https://user-images.githubusercontent.com/32879490/124099704-789ce680-da66-11eb-8b77-2df15929398e.png)

### Possible Solution

I've used toPng and it works just fine.

**Comment by boussadjra** [comment]
Add an explicit background color : 

```
htmlToImage.toJpeg(item, {
              quality: 1,
              style: { background: "white" },
            });
```

**Comment by kikeztw** [comment]
I'm having the same problem :(

**Comment by MonalisaBaltatescu** [comment]
@boussadjra  Thank you! I've tried it and it is working, but still is not the expected output (as toPng method returns). See below the resulting PDF. The image still has a black background on the sections with no content
![image](https://user-images.githubusercontent.com/32879490/125398232-b6c7cd80-e3b7-11eb-9a92-c2c1ce440e2b.png)

**Comment by boussadjra** [comment]
@MonalisaBaltatescu make sure to set an explicit background to the parent element that contains all these sections

**Comment by kru032** [comment]
htmlToImage.toJpeg(item, {
              quality: 1,
              style: { background: "white" },
            });

This worked for me
Thank you!

**Comment by sanislo** [comment]
worked for me as well
