### ISSUE TITLE
Empty image data

### ISSUE THREAD

**Issue by robertnicjoo** [bubkoo/html-to-image#156]
### Expected Behavior

Getting screenshot

### Current Behavior

Not getting screenshot!

### Possible Solution
?!

### Steps To Reproduce

Code below 👇🏻 

### Additional Context

--

### Your Environment

```javascript
var node = document.getElementById('pritable');

htmlToImage.toPng(node)
.then(function (dataUrl) {
  console.log('test', dataUrl);
  download(dataUrl, 'my-node.png');
});
```

Result of  `console.log('test', dataUrl);`

```
<img src="data:,">
```

- html-to-image: ^1.6.2
- OS: Win 10
- Browser: chrome latest

**Comment by ChinmayDeyUI** [comment]
Same problem me too for both png and jpg

**Comment by mgw-sbex** [comment]
Could you update the console.log output, it doesn't look correct based on the code. Thanks
