### ISSUE TITLE
problem with mask css

### ISSUE THREAD

**Issue by fedev21** [bubkoo/html-to-image#157]
Hi thanks so much for this tool! 

I have a problem with the svg in a mask.
The image provided by html-to-image totally ignores the element with the rule css webkit-mask: url ()

![mask-with-html-to-image](https://user-images.githubusercontent.com/60235004/124621574-c479d200-de50-11eb-83ce-1e4f6c645efe.png)

it should look like this

![svgexample](https://user-images.githubusercontent.com/60235004/124625566-4b7c7980-de54-11eb-816b-256bdece1aab.png)

Attached result image, the orange block had a logo

![htmlToImageJPG (2)](https://user-images.githubusercontent.com/60235004/124623225-2d157e80-de52-11eb-80ef-a26c604bb386.jpeg)

- html-to-image: ^1.6.2
- OS: Win 10
- Browser: chrome latest

**Comment by quadlayers** [comment]
+1

**Comment by fedev21** [comment]
I want to keep the issue open.
Thanks!

**Comment by GuitarBro** [comment]
Seems like this is still an issue in latest Chrome (93).

**Comment by quadlayers** [comment]
> Seems like this is still an issue in latest Chrome (93).

Hello mate, have you been able to solve this in some way?

**Comment by GuitarBro** [comment]
Not solved, but I worked around it by rendering out already-masked versions of my images.

**Comment by quadlayers** [comment]
> Not solved, but I worked around it by rendering out already-masked versions of my images.

great, we can offer you a payment for the code
please contact us to quadlayers gmail dot com
