### ISSUE TITLE
Blank image with 1.6.2 version

### ISSUE THREAD

**Issue by Davids89** [bubkoo/html-to-image#160]
Since I updated to 1.6.2, everytime I get a screenshot I get only a blank image. I was checking the last commits and I saw it was changed the way to clone nodes.

### Expected Behavior

With previous version I got a correct screenshot.

### Current Behavior

If I update to 1.6.2, automatically I get blank screenshot.

This is how i got the screenshot since I installed the package.

```js
const element = document.querySelector(identifier)

const params = {
    pixelRatio: 1,
    quality: 1
}

toJpeg(element, params).then(dataUrl => {
    // I have here my image in base64
}).catch(() => {
   // throw error
})
```

Thank you.

**Comment by mgw-sbex** [comment]
If blank is the same as black, I'm seeing this too.
Here is my code:
saveAs(blob, fileName) {
    var elem = window.document.createElement('a');
    elem.href = blob
    elem.download = fileName;
    elem.style = 'display:none;';
    (document.body || document.documentElement).appendChild(elem);
    if (typeof elem.click === 'function') {
        elem.click();
    } else {
        elem.target = '_blank';
        elem.dispatchEvent(new MouseEvent('click', {
          view: window,
          bubbles: true,
          cancelable: true
          }
        ));
    }
    URL.revokeObjectURL(elem.href);
    elem.remove();
  }

  async getPng(elem){
    let blob = await htmlToImage.toPng(elem);
    return(blob);
  }

  capture(id) {
    let elem = document.getElementById(id);
    if (typeof(elem) === undefined) {
      console.log('capture: elem undefined' + id)
      return;
    }
    if (elem != null) {
      this.getPng(elem)
        .then((response) => this.saveAs(response, 'instantreplay.png'));
    }
  };

FYI My image is:
[image-string.zip](https://github.com/bubkoo/html-to-image/files/6946318/image-string.zip)
You can see the one icon in the upper right. The remainder of the image is an iframe playing a video.
There are no CORS errors in the console (or any errors)

**Comment by Cedtron** [comment]
hello 
i think am having the same issue it shows black on the downloaded image like it dosenot read the background image of the my CSS

**Comment by Davids89** [comment]
@vannyle I downgraded the version to 1.6.1 to fix it temporary.

**Comment by SalahAdDin** [comment]
Any answer here?
