### ISSUE TITLE
`background-clip:text` seems not supported

### ISSUE THREAD

**Issue by joaoggnogueira** [bubkoo/html-to-image#162]
### Expected Behavior

![image](https://user-images.githubusercontent.com/10080622/126720407-42719998-b7b5-4c0a-82d9-ecd559669596.png)

### Current Behavior

![image](https://user-images.githubusercontent.com/10080622/126720429-8f648d8a-208c-49d0-b331-5215583ce833.png)

### Steps To Reproduce

Sample of CSS
`
    background-color: #b18207;
    text-shadow: 0px 2px 3px rgba(242,178,14,0.5);
    -webkit-background-clip: text;
    -moz-background-clip: text;
    background-clip: text;
`

1. Create a text using the CSS background-clip property
2. Use the toBlob function and save it as a JPEG image

HTML-To-Image version

There are no errors on the console

- html-to-image:  1.6.2
- OS: Windows NT 10.0; Win64; x64
- Browser :Mozilla/5.0 () AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36 OPR/77.0.4054.27

**Comment by Senzz** [comment]
have same issue

**Comment by paolareyes** [comment]
any updates?
