### ISSUE TITLE
Need help with a performance issue - something related to garbage collection?

### ISSUE THREAD

**Issue by pagarevijayy** [bubkoo/html-to-image#163]
Hello, first of all, thanks for this awesome project! I have a use case where I might need to download an image multiple times (or download multiple images after converting DOM to PNG).

For downloading I'm using this technique.
```  
  let proxyLink = document.createElement("a");
  proxyLink.href = dataURL;
  proxyLink.download = filename;
  document.body.appendChild(proxyLink);
  proxyLink.click();
  document.body.removeChild(proxyLink);
```

Every time I hit download, I see that it takes more time in the subsequent download than the previous one. For example, suppose the first download takes 1500ms, then the second will take 3500ms, and so on. I have added the benchmarking report for 10 iterations below.

An interesting fact is that if I refresh the page after each download, it takes the same time as the first iteration would require. This makes me believe there must be some garbage-collection related issue here. The memory allocated for data URLs in the earlier iterations must be hampering the performance here. The ultimate consequence of this performance issue is that the browser gets hang. 

Do you know a legit way that can help resolve this issue? or some resource I must look into to solve this problem? or maybe change the solution/architecture altogether to solve the use case?

(I am happy to help optimize this library for this use case if I get the solution working and make it universal)

Thanks in advance!

---
case | iteration 1 | iteration 2 | iteration 3 | iteration 4 | iteration 5 | iteration 6 | iteration 7 | iteration 8 | iteration 9 | iteration 10
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
single image | 1416ms | 1699ms | 2170ms | 2598ms | 3054ms | 3512ms | 3933ms | 4378ms | 4891ms | 5341ms
single image (refresh after every download) | 1376ms | 1322ms | 1380ms | 1347ms | 1353ms | 1305ms | 1333ms | 1321ms | 1394ms | 1310ms

**Comment by pagarevijayy** [comment]
Researched a bit. 

The problem could be in [this](https://github.com/bubkoo/html-to-image/blob/17f3a27527da63fca6a0100352c1f883824716d2/src/index.ts#L46) line. Creating a DOM node and then never destroying it?

Interesting thesis: 
When using toPng (which uses toCanvas func) the main thread is blocked all the time. There's a bottleneck.

But while using toSvg the task gets over on the main thread as soon as it should. (which produces a strong case for a leak via creating a DOM element)

**Comment by codingedgar** [comment]
> Researched a bit.
> 
> The problem could be in [this](https://github.com/bubkoo/html-to-image/blob/17f3a27527da63fca6a0100352c1f883824716d2/src/index.ts#L46) line. Creating a DOM node and then never destroying it?
> 
> Interesting thesis:
> When using toPng (which uses toCanvas func) the main thread is blocked all the time. There's a bottleneck.
> 
> But while using toSvg the task gets over on the main thread as soon as it should. (which produces a strong case for a leak via creating a DOM element)

It seems it has a huge perf penalty when generating multiple images, it freezes the main thread for a few seconds when generating ~60 images, maybe we could pass the canvas reference so there's no need to create a new canvas?
