### ISSUE TITLE
ERROR Error: Uncaught (in promise): SecurityError

### ISSUE THREAD

**Issue by samktest** [bubkoo/html-to-image#17]
I have used this module to export html to png  base64 dataurl and pass it to server 
it works fine in Chrome and mozilla but not working in IE 11 it gives error like 

ERROR Error: Uncaught (in promise): SecurityError

please help

**Comment by modwebpl** [comment]
Samge here:

Error inlining remote css file SecurityError: The operation is insecure. core.js:7022:29
Error loading remote stylesheet SecurityError: The operation is insecure. core.js:7019:37
Error while reading CSS rules from https://fonts.googleapis.com/css?family=Lato:300,700&display=swap&subset=latin-ext SecurityError: The operation is insecure. core.js:7034:33

**Comment by goors** [comment]
same here, completely unusable lib :(

**Comment by BenjaminRichardson** [comment]
I was having this issue as well. In my case I think it is related to an HTMLCanvas being "tainted".

You can read more about it https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image

**Comment by maneeshmk** [comment]
Same here:

Error inlining remote css file SecurityError: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
app.js:2149 Error loading remote stylesheet SecurityError: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
app.js:2149 Error while reading CSS rules from https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900|Material+Icons SecurityError: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules

**Comment by Gitesh-Narula** [comment]
Just add `crossOrigin="anonymous` in the link tag of your font, this will fix the error.

**Comment by pitchitmaster101** [comment]
> Just add `crossOrigin="anonymous` in the link tag of your font, this will fix the error.

You saved me, thank you
