### ISSUE TITLE
CORS/Crossdomain Throws an error

### ISSUE THREAD

**Issue by jessejamesrich** [bubkoo/html-to-image#179]
I've recently switched from the other html2Canvas to html-to-image and it seems to be working with the exception of cross domain capturing. I get a cors error. 

```
[Log] Error inlining remote css file – "SecurityError: Not allowed to access cross-origin stylesheet" (vendors~main.chunk.js, line 110581)
[Log] Error loading remote stylesheet – "SecurityError: Not allowed to access cross-origin stylesheet" (vendors~main.chunk.js, line 110581)
```

I know in html2Canvas there is a core option. Is here one in html-to-image?

Can produce on. 

-Node v14.15.5
-Chrome/Safari

**Comment by SalahAdDin** [comment]
Is there any answer here?

**Comment by flipace** [comment]
> Is there any answer here?

We've been able to fix this by adding `crossOrigin​="​anonymous​"​` to the affected link tags.

**Comment by SalahAdDin** [comment]
> > Is there any answer here?
> 
> We've been able to fix this by adding `crossOrigin​="​anonymous​"​` to the affected link tags.

The problem here is all images have `crossOrigin​="​anonymous​` by default. I'm checking it again.
