### ISSUE TITLE
Define DPI

### ISSUE THREAD

**Issue by bkarv** [bubkoo/html-to-image#18]
Thanks for this plugin. Is it possible to define the DPI so we can get better resolution images? I assume the max currently is 96dpi?

**Comment by sztepen** [comment]
Hi I made a very simple change locally that introduces scaleRatio to the options - it is an interim method of setting DPI -- Seems to work fine on my end, I will do a PR when I have time - feel free to ping me about it

**Comment by quantumdot** [comment]
@sztepen I would be interested in the solution you came up with. Thanks!

**Comment by sztepen** [comment]
Got it. Will prepare the code

**Comment by sasithahtl** [comment]
I made the change for that and made a pull request. 

https://github.com/bubkoo/html-to-image/pull/60
