### ISSUE TITLE
margin shift the node inside the frame

### ISSUE THREAD

**Issue by arthurmougin** [bubkoo/html-to-image#189]
When rendering a node with margin set to a non zero value, the image generated is scaled correctly but drifted to the bottom right with the margin delta

### Expected Behavior

node should be fit the rendered image.

### Current Behavior

node drifted from the image by the margin delta.

### Possible Solution

i suppose that forcing a margin:0; to the root node when cloning it would fix the issue. 

### Steps To Reproduce

1. create a node with random content and a margin like 1em or soo
2. render that node
3. append an img from the render

You will be able to see on that the node in the picture is not correctly placed.

### Additional Context

I tested with this dom element
![image](https://user-images.githubusercontent.com/26094902/133935490-992cd589-ea0e-4232-816e-bf396d53e052.png)
and it generated this image :
![cbimage](https://user-images.githubusercontent.com/26094902/133935529-9d9dca6c-817f-4c79-afa0-f5dab092f241.png)

### Your Environment

- html-to-image: "^1.8.1"
- OS: Windows 10
- Browser: vivaldi 4.2 - stable (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.83 Safari/537.36)

**Comment by CoralSilver** [comment]
I agree this is an important issue and should be fixed.

**Comment by kostmika** [comment]
I also agree this is an important issue and should be fixed.

**Comment by lsyeazell** [comment]
I too agree this is an important issue and should be fixed.

**Comment by Selindek** [comment]
This issue is still there

**Comment by GibreelAbdullah** [comment]
Still there. Any workarounds?

**Comment by haibins** [comment]
I also agree this is an important issue and should be fixed.

**Comment by VladimirMikulic** [comment]
Still an issue as of Nov 2023.
