### ISSUE TITLE
backdrop-filter:blur property's effect is missing in results

### ISSUE THREAD

**Issue by Carlos-Henreis** [bubkoo/html-to-image#190]
This css property shows it's effect when toSvg() is used and the svg part of the result is viewed directly without using <img> tag. As soon as you create data uri of that svg and put it as the source for an <img> tag, this property's effects are not shown in image.

This happens in Chrome. Firefox do not have direct support for backdrop-filter property yet.

**Comment by TheFireBlast** [comment]
Also happens in Firefox. You can enable it by setting `layout.css.backdrop-filter.enabled` and `gfx.webrender.all` both to `true` in `about:config` (https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter#browser_compatibility).

This may be related: https://bugzilla.mozilla.org/show_bug.cgi?id=1657997 ("Screenshot doesn't capture backdrop-filter effects")
