### ISSUE TITLE
Google fonts loading issue

### ISSUE THREAD

**Issue by DenverTK** [bubkoo/html-to-image#207]
Google fonts are not being embedded when generating image. Security error CORS issue

**Comment by jessuni** [comment]
I'm getting the same error. Fixed by setting `crossOrigin` to `anonymous` in the request.
`<link href="https://fonts.googleapis.com/css2?family=xyz" rel="stylesheet" crossorigin="anonymous">`

**Comment by tottivega** [comment]
Hey @jessuni that does prevent that error from being thrown, however I still hit the `Uncaught (in promise) RangeError: Invalid string length` error afterwards, which I'm not sure if you're familiar with

**Comment by fsjsd** [comment]
> I'm getting the same error. Fixed by setting `crossOrigin` to `anonymous` in the request. `<link href="https://fonts.googleapis.com/css2?family=xyz" rel="stylesheet" crossorigin="anonymous">`

this worked for me

**Comment by Blackglade** [comment]
> I'm getting the same error. Fixed by setting `crossOrigin` to `anonymous` in the request. `<link href="https://fonts.googleapis.com/css2?family=xyz" rel="stylesheet" crossorigin="anonymous">`

Fixed for me as well! Text kept getting cutoff with my google font.
