### ISSUE TITLE
FONT EMBEDDING SLOWING THINGS

### ISSUE THREAD

**Issue by DenverTK** [bubkoo/html-to-image#208]
The library is loading and embedding all @font face fonts on the page. The library should only embed only the fonts used on the dom. If I request 50 fonts from Google the library will embed them all instead of the used ones on the dom being rendered. This is slowing down image generation

**Comment by cherouvim** [comment]
I confirm that `@font` slows things down significantly (i.e 15 seconds instead of 2 on a page).
