### ISSUE TITLE
It works in Safari

### ISSUE THREAD

**Issue by Finesse** [bubkoo/html-to-image#211]
As I can see on my website, the version 1.9.0 of html-to-image works in Safari 15 as intended (I didn't test in other versions). So this readme note should be removed:

> Safari is not supported, as it uses a stricter security model on <foreignObject> tag. Suggested workaround is to use toSvg and render on the server.

**Comment by pouu69** [comment]
@Finesse 
is it working lower version(ios < 15)? 
As far as I know, there are also issues where images cannot be loaded.

**Comment by Vaneste** [comment]
Not working for me...

**Comment by Finesse** [comment]
@pouu69 @Vaneste Sorry for the long response. I've made a demo page to try `html-to-image`: https://codepen.io/TheFinesse/pen/ExvqJBB

It has a cross-origin image, but the image comes with a `Access-Control-Allow-Origin: *` header. If the image doesn't have the header, the library will leave a blank space in place of the image. AFAIK this is a common browser policy for handling cross-origin images. Anyway, this is a subject for another issue.

Here are my test results (using BrowserStack):

- macOS Safari 15.1: ✅
- iOS Safari 15.1: ✅
- macOS Safari 14.1: ✅ 
- iOS Safari 14.1: ✅
- macOS Safari 13.1: ✅ 
- iOS Safari 13.0: ✅
- macOS Safari 12.1: ✅
- iOS Safari 12.1: ✅
- macOS Safari 11.1: ✅
- iOS Safari 11.0: `SecurityError (DOM Exception 18): The operation is insecure`
- macOS Safari 10.1: `SecurityError (DOM Exception 18): The operation is insecure`

Apparently, the library works starting from Safari 11.1.
