### ISSUE TITLE
Transparent image

### ISSUE THREAD

**Issue by mparpaillon** [bubkoo/html-to-image#22]
Hi, 
Thanks for your work on this lib.

Maybe that's a dumb question but is there a way to generate a PNG image from the DOM with transparency ? No background-color.

Thanks a lot

**Comment by mparpaillon** [comment]
Apparently that's totally possible with this lib. Thanks again

**Comment by Tomassito** [comment]
Is it? Tried using toPng() both with and without the backgroundColor: 'transparent' but couldn't achieve this.
