### ISSUE TITLE
dataUrl returns "data: ,"

### ISSUE THREAD

**Issue by jurajstekla** [bubkoo/html-to-image#222]
Hi guys, im trying to export some charts from my application. Charts are in different places in application and not all of them are visible (on different tab). Then im looping trought my list of charts and if chart is not vissible at that moment (when im not on tab where chart is placed) dataUrl is "data: ," even my chartNode which im getting by "id" looks fine.

My code:

const handleChart = (box) =>
    new Promise(resolve => {
      const chartDiv = document.getElementById('chart' + box.id);
      toPng(chartDiv, { cacheBust: true })
        .then(dataUrl => {
              resolve(dataUrl );
            };
        })
    });

for (const box of boxes) {
      let appendToHeader = '';
      const test = await handleChart(box);
      //do something with dataUrl
     // expected data:base64;image.....
     // getting data: ,
}

### Your Environment
ReactJS

Any ideas ?

- html-to-image: [e.g. 0.1.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by joseteIIo** [comment]
Same problem...

**Comment by chriswetterman** [comment]
Same here. When I changed the element I was targeting from a span to div, it worked okay for PNG (JPG's are black though).

**Comment by gus-tavo01** [comment]
same problem here also :/

**Comment by mrniamster** [comment]
same here :


![image](https://user-images.githubusercontent.com/52563039/156790342-ff967689-2b32-4ad8-b7e6-8ad16673797c.png)
