### ISSUE TITLE
checkbox not displaying checked status

### ISSUE THREAD

**Issue by ffd8** [bubkoo/html-to-image#224]
### Expected Behavior

When saving an image of HTML that contains form checkboxes, it should display if they are checked or not.

### Current Behavior

All checkboxes appear unchecked.

### Possible Solution

Not sure – just started testing this lib from html2canvas, and it already has much better form element rendering! 
This would be icing on the cake..

### Steps To Reproduce

1. Create HTML page with checkboxes:
```
<input type="checkbox" checked>
<input type="checkbox">
<input type="checkbox" checked>
<input type="checkbox" checked>
<input type="checkbox">
```
2. save html-to-image
3. wonder where the checked boxes are....

</p></details>

### Additional Context

What I'm expecting (MacOS screenshot):
![image](https://user-images.githubusercontent.com/570957/145916083-e4ffe8d3-7e20-49c1-ab3c-9c8a8ee4478f.png)

What I'm getting with html-to-image:
![image](https://user-images.githubusercontent.com/570957/145916093-e6b83647-c78d-4e4f-9439-5334e6488f8b.png)

### Your Environment

- html-to-image: 1.9.0
- OS: MacOS 10.13.6
- Browser: Chrome latest

Lastly, in regard to #5 , #41 , #58 – it would be oh so user-friendly if this repo could also include a `/dist` directly with it compiled for browser front-end use without NPM and/or in the readme, suggest a CDN point to access it. Luckily the latest v1.9.0 min hosted on [cdnjs](https://cdnjs.com/libraries/html-to-image) worked..

**Comment by ffd8** [comment]
Quick followup, just realized that `select` (dropdowns) are not capturing with their selected value.. it is however working just fine to capture the `colorPicker` element...

**Comment by Kritten** [comment]
Please reopen this issue. It is the same for me. 
No rendered checked states neither for Radiobuttons nor for Checkboxes

**Comment by ShaMan123** [comment]
+1

**Comment by ffd8** [comment]
Yeeeah, thanks @ShaMan123 for #245 – looking forward to it being merged when approved.

**Comment by ShaMan123** [comment]
I guess this repo is neglected.
Hopefully maintainers will revive it as it is an excellent piece of work.
