### ISSUE TITLE
Doesn't save background image on iPhone, but works on web  — CORS issue?

### ISSUE THREAD

**Issue by thestevenmellor** [bubkoo/html-to-image#228]
I have an app that uses html to image to make screenshots. 

it's react / capacitor app that runs on my iOS device. 

It renders the preview of the background image on the device, but when I save it to the Photo gallery, the background image is black. 

css gradients seem to save perfectly, too. 

It also works perfectly on desktop / web — so this is strictly a mobile issue. 

Could it be a CORS issue? 

Trying to move away from html2Canvas as htmlToImage has higher quality. 

Here are the two screenshots. 

`async getJpg(){
await htmlToImage.toJpeg(document.getElementById('capture'), { quality: 1 })
  .then( (dataUrl) => {
    var link = document.createElement('a');
    link.download = 'my-image-name.jpeg';
    link.href = dataUrl;
    
    this.setState({screenshotUrl: link.href});
    console.log(link.href);
    if (isMobile) {
      Clipboard.write({image: link.href });
      
      Haptics.impact({ style: ImpactStyle.Heavy });
      const media = new Media();
      media.getAlbums().then((res)=>{
        let myAlbums = res.albums;
        media.savePhoto({ path: link.href })
        .then(
          console.log('success', link.href),
          this.savedToast()
          )
        .catch(console.log('error'));
        
      });
      
    }else{
       //Downloaded file
      link.click();
      this.setState({myClipboardImg: link.href});
      this.savedToast()
    }
    // var w = window.open("");
    // w.document.write(myimage.outerHTML);
  });
}`

![IMG_0164](https://user-images.githubusercontent.com/24770680/147980916-e12ad65f-e133-4bd6-a390-e0894826b02f.JPG)
![IMG_0165](https://user-images.githubusercontent.com/24770680/147980918-19ef1f97-ee3a-452d-b98e-14c4bdd3befc.PNG)
![IMG_0167](https://user-images.githubusercontent.com/24770680/147980927-689f834d-883b-4d1c-b6be-29808bcb11bc.JPG)

**Comment by petergeorgas** [comment]
I am kinda new to the world of what this library is actually doing, but I am experiencing something similar, except it doesn't work on web. I am making sharable Tweet Snippets like yourself, but the profile picture returned from my calls to the Twitter API does not appear in the same image. See #238 for more info.
