### ISSUE TITLE
Converting HTML containing img elements to PNG results in images not loading

### ISSUE THREAD

**Issue by petergeorgas** [bubkoo/html-to-image#238]
### Expected Behavior

When converting HTML that contains `<img>` elements, the `<img>` elements should always complete loading before the HTML is converted to an image.

### Current Behavior

In some situations, specifically with Twitter profile pictures as the source, the `<img>` elements do not load  in time, and when the HTML is converted to a, say PNG for example, the image(s) are not present.

Some images load just fine, just not these, which kinda sucks -- I need Twitter profile pics to load. 

### Possible Solution

This must be a result of the sequence of events that occur  when a function like `toPng` is called. I have attempted to convert the HTML to a blob instead, and the same issue prevails.

### Steps To Reproduce

1. Create an HTML `<img src="https://pbs.twimg.com/profile_images/1354479643882004483/Btnfm47p_bigger.jpg"/>` element. This source is good because it is a situation where the image will not appear.
2. Convert HTML to PNG
3. Save PNG to computer.

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Additional Context

I am creating a basic application that allows users to paste in a link to a Tweet, where my application will then render the contents of the Tweet on a React component on a customizable background. Once they have customized the Tweet and background to their liking, they can choose to export it as a PNG. 

The HTML page, showing the Tweet component:
![image](https://user-images.githubusercontent.com/21143531/149850726-5e711e5c-e506-40b2-8627-01c402fc9dfd.png)

The resulting image (exported as PNG):
![image](https://user-images.githubusercontent.com/21143531/149850784-d36b88f2-4f16-45ed-9ed1-ab3d47188373.png)
[This branch](https://github.com/petergeorgas/Social-Media-Snippets/tree/feature/implement_customizeable_preview) contains my features I implemented. `components/SnippetPreview.tsx` contains the logic for exporting.

### Your Environment

- html-to-image: 1.9.0
- OS: Windows 10, macOS, etc. 
- Browser: Firefox, Chrome, Brave, all of them.

**Comment by delia-m** [comment]
I had same issue with `toJpeg` and just worked round to use div and set image as a background rather than using img element 
This worked for me but it would be great if img element is working

**Comment by petergeorgas** [comment]
> I had same issue with `toJpeg` and just worked round to use div and set image as a background rather than using img element This worked for me but it would be great if img element is working

I honestly never even thought to try this. I will give it a go, it sounds promising!
