### ISSUE TITLE
<Image/> inside a div not rendering in toPng() in NextJS

### ISSUE THREAD

**Issue by yashpaneliya** [bubkoo/html-to-image#242]
I am trying to capture a functional component as an image that contains user input images. When I download the component using toPng(), the text and other elements get captured perfectly but the images inside it don't.

### Expected Behavior
![image](https://user-images.githubusercontent.com/58077762/151745166-0667a908-7910-4c3a-aa39-ecab8d1aa39c.png)

This is the component I want to capture as png.

### Current Behavior
![image](https://user-images.githubusercontent.com/58077762/151745207-5ee50571-3df0-48f3-97a5-ea8667690411.png)

When I download the component as png using toPng() then it doesn't render the images inside the component.

### Possible Solution

I guess the reason behind this bug is that the images are user input images (through ```input:file```). Because when I try static images in place of user input images, it renders them perfectly

### Steps To Reproduce

```
const ref = useRef();

  const handleDownload = async () => {
    toPng(ref.current, { cacheBust: true })
      .then((dataUrl) => {
        const link = document.createElement("a");
        link.download = "sample.png";
        link.href = dataUrl;
        link.click();
      })
      .catch((err) => {
        console.log(err);
      });
  };
```

<details><summary>Error Message & Stack Trace</summary><p>

```txt
getBlobFromURL.js?e567:43 GET blob:http://localhost:3000/3867648e-6f65-405a-ab8f-64cde70ac725?1643608524355 net::ERR_FILE_NOT_FOUND
```

</p></details>

### Your Environment

- html-to-image: 1.9.0
- OS: Windows10
- NextJS: 12.0.8
- ReactJS: 17.0.2
- Browser: Brave 1.34.81 and Chrome 97.0.4692.99

**Comment by yashpaneliya** [comment]
not stale

**Comment by petergeorgas** [comment]
#238 Seems to be similar. Is this a CORS issue? Are your images links or are they stored locally?

**Comment by yashpaneliya** [comment]
Actually, I was rendering locally stored blob images so that was the reason behind the issue. 

I converted the blobs to `dataURL` using `FileReader` and now it works fine and all the images are captured properly in the screenshot.
