### ISSUE TITLE
for LWC application htmltoImage throwing error TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

### ISSUE THREAD

**Issue by rahultokase** [bubkoo/html-to-image#243]
For LWC application when tries generating the image getting the below error 
TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

Please check the below url.
https://webcomponents.dev/edit/b0l5xqbc1YNEyfV9p0eW
### Expected Behavior
It should generate the Image.

### Current Behavior
Throwing an error with following message
Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

### Steps To Reproduce
Please use the below URL for reproducing the issue.
https://webcomponents.dev/edit/b0l5xqbc1YNEyfV9p0eW

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- html-to-image: [e.g. 0.1.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by pl4nty** [comment]
This has been reported in #54, #79, and #174 with no resolution. I'm experiencing it too

**Comment by pl4nty** [comment]
bump
