### ISSUE TITLE
svg path element missing for exported image

### ISSUE THREAD

**Issue by Shilpa-K07** [bubkoo/html-to-image#249]
I'm trying to get the snapshot of the div which contains svg element.  Lines are missing in the snapshot which are drawn using svg path element. Also its failing to load mdi icons.  I'm using vue 2.6.11.

Code to draw line:
`<svg
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      height="100" width="300">
      <path 
      :d="path" stroke="blue" stroke-width="2px" />
    </svg>`

**Using toPng method**
<img width="960" alt="SnapShot-png" src="https://user-images.githubusercontent.com/70196456/153379943-00b1d1c2-7c50-4db4-8c90-47975e5c4ea0.png">

Using toSvg
<img width="960" alt="SnapShot-svg" src="https://user-images.githubusercontent.com/70196456/153380353-39f036c5-69a3-4b4b-89ea-9cf777e84822.png">

Original view
<img width="960" alt="original" src="https://user-images.githubusercontent.com/70196456/153381947-50b84d3d-49af-4027-997e-d0e009ea5ef1.png">

**Comment by rafaelhancke** [comment]
Hi !!

**Comment by goforu** [comment]
any progress?

**Comment by georgezouq** [comment]
any solution? @Shilpa-K07
