### ISSUE TITLE
SVG + Azure Private blob service

### ISSUE THREAD

**Issue by sagarox** [bubkoo/html-to-image#25]
I am facing an issue with SVGs which is rendered from Azure blob service. If an image is made publicly available it's working perfectly fine. But if we make blob container private than Package is unable to generate an image from it.

**Comment by sagarox** [comment]
I narrowed the problem and found the issue.
Issue lies in `getMimeType` function,

let's say my url is 
https://container.blob.core.windows.net/sample-name/1565703778478.svg?st=2019-08-19T09%3A06%3A53Z&se=2019-08-19T09%3A21%3A53Z&sp=r&sv=2018-03-28&sr=b&sig=S0fAYWl%2F8zulEd0u2N2mTV7YCMZVaystQa0Jf%2FcZ5bI%3D

So getMimeType is unable to identify extention, it returns extention as `svg?st=2019-08-19T09%3A06%3A53Z&se=2019-08-19T09%3A21%3A53Z&sp=r&sv=2018-03-28&sr=b&sig=S0fAYWl%2F8zulEd0u2N2mTV7YCMZVaystQa0Jf%2FcZ5bI%3D` instead of just `svg`.
In case of Other images rather than SVGs everythings works fine. We need to update regex used for checking URL.

**Comment by sagarox** [comment]
+ keeping alive. This will happen for aws services as well

**Comment by sagarox** [comment]
Keep Alive

**Comment by pitchitmaster101** [comment]
any solutions?
