### ISSUE TITLE
CSS Grid broken on latest Chrome

### ISSUE THREAD

**Issue by hristoiankov** [bubkoo/html-to-image#258]
The CSS Grid option `grid-template-areas` no longer works properly when converted to canvas on the latest version of Chrome (Version 99.0.4844.51).

### Expected Behavior

![image](https://user-images.githubusercontent.com/35353708/157521963-8e167161-44c2-493d-a64c-f26920000984.png)

### Current Behavior

![image](https://user-images.githubusercontent.com/35353708/157522020-8c706c89-8fd7-4e9d-9960-2516e59144de.png)

### Steps To Reproduce

```
.card {
  display: grid;
  grid-template-columns: 100px auto;
  grid-template-rows: auto 100px 100px;
  grid-template-areas: 
    "header header"
    "one two"
    "three four";
  justify-items: center;
}
.card h1 {
  grid-area: header;
}
.card .i1 {
  grid-area: one;
}
.card .i2 {
  grid-area: two;
}
.card .i3 {
  grid-area: three;
}
.card .i4 {
  grid-area: four;
}
```

```
<div class="card">
  <h1>Thesis Paper</h1>
  <div class="i1">A</div>
  <div class="i2">B</div>
  <div class="i3">C</div>
  <div class="i4">D</div>
</div>
```

https://jsfiddle.net/Lk94cwxz/4/

### Environment

- html-to-image: 1.9.0
- OS: Windows, Ubuntu
- Browser: Version 99.0.4844.51 (Official Build) (64-bit)

**Comment by chahu** [comment]
I also encountered this bug. The below codepen example might help test. Works on fine on latest Safari & Firefox, but is broken on latest Chrome (99.0.4844.51), I believe it works on previous Chrome versions. Probably a Chrome bug.

https://codepen.io/chahu/pen/NWXGqxm

**Comment by pawelkrystkiewicz** [comment]
@chahu yes this is a chromium bug, you can track it here https://bugs.chromium.org/p/chromium/issues/detail?id=1305997

**Comment by hristoiankov** [comment]
I tried to consolidate all the GitHub repository issues that I know of into that Chromium ticket.  It is nice to see the Chromium team addressing it and we might be getting a fix in the 100 or 101 revision.

**Comment by AndrewTBurks** [comment]
from what I can tell, the Chromium bug report shows that the fix won't land until Chrome 102 - for now, this issue is not yet stale

**Comment by chahu** [comment]
Yes, this is still affecting the current version of Chrome.
For anyone needing a workaround here's one solution: https://codepen.io/chahu/pen/abqobdL

**Comment by hristoiankov** [comment]
I'm closing this issue since Chrome's latest version is past the fix version.

**Comment by chrisglein** [comment]
Has anyone verified this fix with the latest versions of Chrome? I tried 103 and now 104 and the issue still repros for me.

**Comment by chahu** [comment]
> Has anyone verified this fix with the latest versions of Chrome? I tried 103 and now 104 and the issue still repros for me.

Works for me now, on `Version 103.0.5060.134 (Official Build) (64-bit)`. If I open the jsfiddle or codepen testcases from above html-to-image renders correctly now.

**Comment by chrisglein** [comment]
> > Has anyone verified this fix with the latest versions of Chrome? I tried 103 and now 104 and the issue still repros for me.
> 
> Works for me now, on `Version 103.0.5060.134 (Official Build) (64-bit)`. If I open the jsfiddle or codepen testcases from above html-to-image renders correctly now.

Hmm... so I had a repro in my own source, which I've reduced here:
https://codepen.io/papasnewbag/pen/qBoMeqy

Result shown:
![image](https://user-images.githubusercontent.com/26607885/184455585-5a021878-3434-4b8e-b8c6-c66bce649c6d.png)

Output of html-to-image:
![image](https://user-images.githubusercontent.com/26607885/184455609-2e12aecf-e17e-4e3a-9248-0910f7af56e0.png)

Note that this is the difference of removing the `grid-template-rows` property from the CSS. So it seems that isn't making it over. Maybe not the same as that bug, but very similar in that it seems a grid property isn't serialized.

I've been reproing this for awhile, but currently on `Version 104.0.5112.81 (Official Build) (64-bit)`.
Can someone else confirm they are also seeing this? If so it seems like I need to open an issue against Chromium.

**Comment by chahu** [comment]
@chrisglein I can confirm your link does not render properly with "Chrome 104.0.5112.79 (Official Build) (64-bit)". 
I'm guessing you could re-write your grid css to workaround this issue (maybe using grid-template-areas), but it does look like something is still broken with Chrome's CSS grid implementation for your case.
