### ISSUE TITLE
Height / width options appear not to work as might be expected

### ISSUE THREAD

**Issue by rjconrad** [bubkoo/html-to-image#26]
When I  set the width option, I had hoped that the contents (which are 100% width) would scale to fit the given dimensions. Instead I get an image that is the size specified, but the contents remain at the size they are on the page.

I'd be happy to provide more details and an example if you're willing to look into this.

Thanks for the great library!

**Comment by gustavochavarria** [comment]
Please you can check my lib: https://www.npmjs.com/package/save-html-as-image

**Comment by thisizkp** [comment]
@rjconrad It's been a while, but have you figured out any solution for this? I'm facing a similar problem now.

**Comment by rjconrad** [comment]
I ended up setting the size on the html element instead. (For my case, so the user didn’t have to see that, I had another copy of the same DOM nodes positioned offscreen that I could set to be the size I wanted for the image.)

**Comment by thisizkp** [comment]
👍, thanks for the response. I didn't need it for now but could use the above trick if it comes down to that.
