### ISSUE TITLE
Image renders improperly (text wraps in output image, but not in input HTML)

### ISSUE THREAD

**Issue by nikkwong** [bubkoo/html-to-image#261]
I'm having an issue where the input image is not matching the output image. The input image is 1st, and the output is 2nd:
![Screen Shot 2022-03-20 at 3 32 48 PM](https://user-images.githubusercontent.com/8837416/159188865-b2a45ec4-2fc0-46e2-b149-89a087dfe9a1.png)

![Screen Shot 2022-03-20 at 3 32 59 PM](https://user-images.githubusercontent.com/8837416/159188868-0200a027-048b-4381-af31-30258b25aa69.png)

In the output image, the image is cropped unfortunately. I believe it's caused by the fact that the text on the bottom rows are wrapping in the output, but do not in the input. I'm experiencing this on all browsers. Has anyone encountered this or know of a fix?

Thank you.

**Comment by Oluwatobi-beebittech** [comment]
Hi @nikkwong . Can you put in a CodeSandbox link for easy replication of the issue?

**Comment by pinstripeninjas** [comment]
I encountered the same issue, but had difficulty replicating it on a smaller scale in CodeSandbox. Adding 1px of margin to the text element managed to work as a quick fix.

**Comment by ABHIDEB380** [comment]
"not-stale" I also encountered the same issue can anyone please solve it?

**Comment by akshay-nm** [comment]
I'm experiencing the same issue. Tried Adding Line breaks, but html-to-pdf always wraps the last word in the line.

**Comment by ABHIDEB380** [comment]
> I'm experiencing the same issue. Tried Adding Line breaks, but html-to-pdf always wraps the last word in the line.

I have tried increasing the width of the text then it works but the problem is I have to manually give every text the width of 100% and this is a headache. please resolve this issue.

**Comment by jacobchrismarsh** [comment]
I also am dealing with this.

**Comment by socram8888** [comment]
Please try with our fork: https://www.npmjs.com/package/@rigocorp/html-to-image

This one applies [some CSS fixes](https://github.com/RigoCorp/html-to-image/blob/master/src/cssFixes.ts) if running on Chromium to improve rendering accuracy.

**Comment by ABHIDEB380** [comment]
@socram8888 hey I am not able to update my version to ur current version I tried npm install html-to-image@1.10.0 command but I got some error saying its not available, I also tried npm install html-to-image@latest but its update to the version 1.9.0. Can u suggest me some thing that can be usefull?

**Comment by ABHIDEB380** [comment]
`PS C:\Users\abhi\Desktop\web apps\AiPalette\aipalette> npm install html-to-image@1.10.0
npm ERR! code ETARGET
npm ERR! notarget No matching version found for html-to-image@1.10.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.`

@socram8888 thats the error I was getting

**Comment by socram8888** [comment]
@ABHIDEB380 it's in another package name - `@rigocorp/html-to-image`.

Try using `npm install @rigocorp/html-to-image`.
