### ISSUE TITLE
creates is blank image

### ISSUE THREAD

**Issue by sarvinstyle** [bubkoo/html-to-image#264]
I use this code to convert div to image , but the child tags is not capturing and the images is blank image
toPng(ref.current, { cacheBust: true, })
      .then((dataUrl) => {
        console.log(dataUrl);
      })
      .catch((err) => {
        console.log(err)
      })

<div ref={ref}>
<p>WxH </p>
</div>

**Comment by mieky** [comment]
I had the same issue, which in my case was about trying to render something that contains `display: grid` elements. Worked if I changed them to a regular `display: block`. This is due to a recent Chromium bug, tracked in https://github.com/bubkoo/html-to-image/issues/258.

**Comment by winiel559** [comment]
I just faced the same problem with <span ref={ref}>, changed <span> to <div> solved it
