### ISSUE TITLE
How we can apply style

### ISSUE THREAD

**Issue by arslan-butt** [bubkoo/html-to-image#266]
Hi there,
First of all, thank you for sharing this awesome library.

I would like to know how we can apply style property to the `div` before covert to the image

**What currently I have:**
`<div style="top: 30px; left: 50px;"> --- </div>`

**What I want**
`<div style="top: 0; left: 0;"> --- </div>`

**Comment by brumm** [comment]
https://github.com/bubkoo/html-to-image#style

**Comment by arslan-butt** [comment]
I already used this, it actually changes the original `style` of the `div`, which is not good. Now I'm making a temporary clone of the required `div `and adding a new CSS `style` and after exporting to the image, deleting this temporary `div` , which is working perfect :blush:
