### ISSUE TITLE
SVGs that use an image with the href attribute don't include the references images

### ISSUE THREAD

**Issue by williammetcalf** [bubkoo/html-to-image#27]
Svgs that have an `<image href="somelink.svg" />` element do not have the referenced image included in the exported image. 

Demo link: https://codesandbox.io/s/html-to-image-xlinkhref-bug-17fq2 

Note that in the example the red line in the svg is correctly exported to prove that it partially works, but there is no image from the `href` attribute

**Comment by phantomodm** [comment]
@williammetcalf  Hello William.. Did you found a solution to this problem?
