### ISSUE TITLE
Unable to get image screenshot from embed object

### ISSUE THREAD

**Issue by theone3nu** [bubkoo/html-to-image#273]
### Expected Behavior

Thanks for the great library. I have been using this without so much issues. I am stucked with one scenario. I want to capture a screenshot when i have object `<object data={url} />` and data is a external url. But i am not getting image.  That url can be any pdf url or image url. How to capture screenshot from object.

### Steps To Reproduce

`		<object data='https://www.geeksforgeeks.org/wp-content/uploads/Geek_logi_-low_res.png' width={40} height={40} />`

- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by hedikarray1** [comment]
Have you fixed This Issue?
