### ISSUE TITLE
Not able to open downloaded SVG in Illustrator, Photoshop, or SVG editors

### ISSUE THREAD

**Issue by adurgavich** [bubkoo/html-to-image#274]
When using the htmlToImage.toSvg function to generate an SVG, it seems that browsers and image preview tools are able to display the image; however, SVG editors (such as Adobe Illustrator and Photoshop) show the downloaded SVG as a blank image.

### Expected Behavior
Expected bahavior is that the file can be opened by SVG editors and show the image that was downloaded as part of the SVG (similar to what is shown in the web browser or image preview tools when viewing the SVG file).

### Current Behavior
SVG editors (such as Adobe Illustrator and Photoshop) show the downloaded SVG as a blank image.

### Steps To Reproduce
1. Add the necessary html-to-image library to the page:
```
import * as htmlToImage from 'html-to-image';
import { toPng, toJpeg, toBlob, toPixelData, toSvg } from 'html-to-image';
```

2. Attach the following snippet to a click event on a web page where "element_id" is your element ID to target:
```
htmlToImage.toSvg(document.getElementById(element_id))
    .then(function(dataUrl) {
        var element = document.createElement('a');
        element.setAttribute('href', dataUrl);
        element.setAttribute('download', 'mySvg.svg');
        element.style.display = 'none';
        document.body.appendChild(element);
        element.click();
        document.body.removeChild(element);
    });
```

3. Use an SVG editor like Adobe Illustrator/Photoshop or even https://boxy-svg.com/app to open the SVG and notice the blank file.

### Example File
![facebook-ad-mockup](https://user-images.githubusercontent.com/6091861/167730013-da2f8d11-b70c-4454-a32c-69f71a1a437f.svg)

### Your Environment
- html-to-image: ^1.9.0
- OS: macOS, Windows
- Browser: Chrome, Firefox, Safari, Edge

**Comment by pmartiner** [comment]
we had that issue as well. the problem is how the library parses the HTML code to SVG. if you inspect the SVG code, you can see there's a `foreignObject` element and inside it, the HTML code that the library tried to parse. if i remember correctly, due to security reasons, most (if not all) editors won't be able to open `foreignObject`s since its content is not a valid XML SVG element

**Comment by seve** [comment]
> we had that issue as well. the problem is how the library parses the HTML code to SVG. if you inspect the SVG code, you can see there's a `foreignObject` element and inside it, the HTML code that the library tried to parse. if i remember correctly, due to security reasons, most (if not all) editors won't be able to open `foreignObject`s since its content is not a valid XML SVG element

@pmartiner is there a known workaround?

**Comment by SamuelMichelRiad** [comment]
Bump
