### ISSUE TITLE
Throwing an error after Chrome update 

### ISSUE THREAD

**Issue by gurkiran4you** [bubkoo/html-to-image#290]
### Expected Behavior
Should generate Canvas

### Current Behavior
Throws an error 

### Possible Solution
Its working on old chrome versions , something changed which might have broken it

### Steps To Reproduce

Use any method to create canvas/jpeg/png , it throws the below error

<details><summary>Error Message & Stack Trace</summary><p>
isTrusted: true <br>
bubbles: false <br>
cancelBubble: false <br>
cancelable: false <br>
composed: false <br>
currentTarget: null <br>
defaultPrevented: false <br>
eventPhase: 0 <br>
path: [img] <br>
returnValue: true <br>
srcElement: null <br>
target: null <br>
timeStamp: 9531 <br>
type: "error" <br>
```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- html-to-image: [1.9.0]
- Windows 10 pro - 16GB
- Browser: [chrome Version 103.0.5060.66 ]

**Comment by kaushalm** [comment]
Hi, @gurkiran4you is this issue resolved, I see it is marked as closed.

**Comment by gurkiran4you** [comment]
> Hi, @gurkiran4you is this issue resolved, I see it is marked as closed.



> Hi, @gurkiran4you is this issue resolved, I see it is marked as closed.

Yep , an extra "0" in a toggleable html was causing it to fail, coincidently chrome update happened around the same time. 

So, if you have a malformed html, I guess it just fails without any proper error message.
