### ISSUE TITLE
Bundle with html-to-image and Download (all in one)

### ISSUE THREAD

**Issue by gustavochavarria** [bubkoo/html-to-image#30]
Hi.
I'm creating a repo. that use **Html-to-image** and **file-saver** packages.

My intention is to make easy the process to the user with less experience.
Also. I'm writing little hacks for work with some SVG (FontAwesome tested) and work in safari.

https://github.com/gustavochavarria/save-html-as-image
https://www.npmjs.com/package/save-html-as-image

Pull request are welcome

Thanks.

**Comment by alessandrobelli** [comment]
why you just didn't make a pull request for this package? Also your package seems to just download the image, I don't need that. I would just need to solve the safari problem...

**Comment by gustavochavarria** [comment]
@alessandrobelli the problem with safari they're coming from SVG. I convert every svg to png with another package. So the size of the project would be increased.

About the download, this was my need... so.. I made this package and share with us.
