### ISSUE TITLE
Commenting on an issue triggers a rebase

### ISSUE THREAD

**Issue by rooby** [bubkoo/html-to-image#319]
### Expected Behaviour

I should be able to comment on an issue without triggering a rebase.

### Current Behaviour

I comment on an issue and it triggers a rebase action, then I get an email saying "Rebase: All jobs have failed".
Seems like this may also be affecting PRs, as this issue seems similar: #150 

### Steps To Reproduce

Comment on an issue and wait for the email.
Also see the actions tab. Here is an example of a run: https://github.com/bubkoo/html-to-image/actions/runs/3110465116

**Comment by bubkoo** [comment]
@rooby the `rebase` workflow has been removed.
