### ISSUE TITLE
support webp format

### ISSUE THREAD

**Issue by lili21** [bubkoo/html-to-image#326]
### Expected Behavior

webp format image should get correct contentType

### Possible Solution

https://github.com/bubkoo/html-to-image/blob/f0b3cdf53836475e4a30e8a903f79e5561fec9c9/src/mimes.ts#L3-L14

we can add the webp property to the `mimes` object

**Comment by happy-func** [comment]
+1

**Comment by pixelninja** [comment]
+1

**Comment by pixelninja** [comment]
and future proof it with avif format too ;)
