### ISSUE TITLE
Stop font download

### ISSUE THREAD

**Issue by SupriyaRaikhelkar** [bubkoo/html-to-image#34]
Every time call to htmlToImage.toPng() downloads font

**Comment by hijamoya** [comment]
I face the same issue, how can we stop it to download every time.

**Comment by seahindeniz** [comment]
Here is a GIF of the downloads on my case

![a328b960-3b91-4b85-a6c8-a7ab09de1daf](https://user-images.githubusercontent.com/5789670/99081886-7ddf1b00-25d4-11eb-8726-224273e75e90.gif)
