### ISSUE TITLE
Library works as expected locally, but fonts do not load properly in production environment (Correct base64 string, incorrect image)

### ISSUE THREAD

**Issue by chanzer0** [bubkoo/html-to-image#340]
### Description

When using the library locally, calling `.toJpeg()` works as intended, providing the following image:
![LT30-Index_2022_10_29-2022_11_29 (17)](https://user-images.githubusercontent.com/25206712/204642050-f882e60a-4a8a-44c5-b8fc-2795ca82bc80.jpeg)

However, in production, with the same codebase, the following image with incorrect fonts is generated (even though the fonts render just fine on the actual page): 
![LT30-Index_2022_10_29-2022_11_29 (21)](https://user-images.githubusercontent.com/25206712/204642114-be51dd60-7653-4f01-a71d-4accaabc6438.jpeg)

**Update**
I believe the issue lies somewhere in how the package is handling network requests. Locally, we can see that successful requests are made to the fonts:
![image](https://user-images.githubusercontent.com/25206712/204847016-613b78c0-c8b8-4063-a426-94a0fa8deb28.png)

However, in production, these requests are not made:
![image](https://user-images.githubusercontent.com/25206712/204847118-b5412acb-b121-4ef0-b2a2-95b49f31fb6d.png)

I'm not sure why, but therein lies the issue.

**Update 2**
What's even weirder is I'm `console.log`ing the response from `.toJpeg()` as follows:
```
.toJpeg(node, {
	cacheBust: true,
})
.then((dataUrl: string) => {
	console.log(dataUrl);
	const link = document.createElement('a');
	link.download = `Index_${dayjs(startDate).format(
		'YYYY/MM/DD',
	)}-${dayjs(endDate).format('YYYY/MM/DD')}.jpeg`;
	link.href = dataUrl;
	link.click();
});
```

And when I plug this base-64 string into an online image viewer/decoder, the output is correct (Even though the downloaded image is incorrect:

![image](https://user-images.githubusercontent.com/25206712/204875699-b38d7637-9ca3-4b1a-a91c-78ecfcaaa40f.png)

### Expected Behavior

Fonts loaded in page should be styled and applied properly to the generated element.

### Current Behavior

Font loaded and present in the page are not applied properly to the generated element

### Steps To Reproduce

A live example of this can be found [at this url](https://luckytrader.com/nft/market-index/lt30) by clicking on the "download image" icon present in the graph.

`globals.css`
```
@font-face {
    font-family: 'DM Sans';
    src: url('/fonts/DMSans-Regular.woff2') format('woff2');
    font-weight: 400;
    font-display: swap;
}
@font-face {
    font-family: 'Inter';
    src: url('/fonts/Inter-400.woff2') format('woff2');
    font-weight: 400;
    font-display: swap;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
```

`component.tsx`
```
const handleDownloadClick = async (): Promise<void> => {
	const node = document.getElementById(chartId);

	const htmlToImage = await import('html-to-image');

	htmlToImage.toJpeg(node, { quality: 1 }).then((dataUrl: string) => {
		const link = document.createElement('a');
		link.download = `LT30-Index_${dayjs(startDate).format(
			'YYYY/MM/DD',
		)}-${dayjs(endDate).format('YYYY/MM/DD')}.jpeg`;
		link.href = dataUrl;
		link.click();
	});
};
...
return (
    <div id={chartId}>]
        ....
        <div onClick={() => handleDownloadClick()} />
        ....
    </div>
)
```

### Your Environment

- html-to-image: "^1.10.8",
- OS: Windows + Mac (latest versions)
- Browser: Chrome + Firefox (latest versions)

**Comment by zackbiernat** [comment]
We had to append the desired fonts / CSS to the target node.
```
        const targetNode = document.getElementById(targetId);
        
        const styleElement = document.createElement('style');
        styleElement.textContent = `
            @font-face {
                  # ...
      
            }
            # Other required styles.
        `;
        targetNode.appendChild(styleElement);

       // Use library to convert targetNode to an image type.
      // ...
```

**Comment by chanzer0** [comment]
@zackbiernat's suggested implementation above is how we resolved this issue
