### ISSUE TITLE
Fonts not transferred to image

### ISSUE THREAD

**Issue by mister-hunter** [bubkoo/html-to-image#35]
The fonts don't get transferred to the png image when I use `htmlToImage.toPng(node)`.

I use the latest version of Chrome and your package

![image](https://user-images.githubusercontent.com/49814847/69881604-74767900-12c5-11ea-9fd2-2f17d760cb98.png)

**Comment by Dj-jom2x** [comment]
agreed

**Comment by alqamabinsadiq** [comment]
Bump

**Comment by MaciejWira** [comment]
Try loading fonts locally and not through web (eg. from google fonts page). It worked for me.

**Comment by real-jacket** [comment]
Do anyone resolve this ? It works well in my local computer but works bad in server just like this.
