### ISSUE TITLE
Some SVG elements are not visible on resulting image

### ISSUE THREAD

**Issue by AndrewN93** [bubkoo/html-to-image#357]
### Some elements from the chart missing

There is a bug on attempt to convert chart (```Highcharts```in my case) into image. I have a chart with circles on it, and if I try to generate image last circles on the chart are missing. This happens when width of the chart is >1000px.
Highcharts supports other shapes such as ```triangle``` and they are all displayed on result image, so the problem is only for circle shape.

### Expected Behavior
All elements should be on the image

### Current Behavior
Circles at very end of the chart are absent on image.

### Steps To Reproduce
1. Visit reproducable [demo here](https://stackblitz.com/edit/typescript-oknqty?file=index.html,index.ts,package.json)
2. Click on download button
3. Check the image

Notice: There are 10 circles on the chart on the page, but only 7 circles on the image.

### Your Environment
- html-to-image: 10.3.2

**Comment by Jaylyn-Barbee** [comment]
Tracking! My problem is that it doesn't properly get the background image of my div, so it shows everything but the background image.
