### ISSUE TITLE
It's not working with Iframes

### ISSUE THREAD

**Issue by nigellima** [bubkoo/html-to-image#36]
Is there any workaround to make it work with child iframes?
I've been using this package for a few months and it was working like a charm. But now I had to insert iframe elements in my page and they appear blank in the final image.

Here is the piece of code which I'm using in my Angular application:

```
htmlToImage
   .toPng(this.contentAreaRef.nativeElement)
   .then((image: string) =>  {
      this.dashboard.thumbnail_base64 = image;
   });
```

Thanks in advance

**Comment by me2mitesh** [comment]
Hi,

I am also stuck in this issue. Did you find any other solution ?

Thanks in advance

**Comment by nigellima** [comment]
@me2mitesh hey, so, I kinda found out that it was not possible to generate the screenshot of the page with an inframe in it due to browser security issues. So I gave up on trying it
