### ISSUE TITLE
Placeholder color is not correct

### ISSUE THREAD

**Issue by hiep294** [bubkoo/html-to-image#373]
I have an input that has a placeholder, the input's placeholder is grey. But when using toPng, in the image, the placeholder is black.

### Expected Behavior

in the image, the placeholder should be grey

### Current Behavior

in the image, the placeholder is black

### Steps To Reproduce

link: https://codesandbox.io/s/thirsty-sunset-k7nk51?file=/src/App.tsx

1. style placeholder
2. click btn "to png" to export html to png
3. in output png, the placeholder is not styled

**Comment by SUCHMOKUO** [comment]
Just have looked at the code and found some informations about this bug, so I put it here for anyone who wants to contribute :)

For now only the `::before` and `::after` are cloned when doing the screenshot, ideally we just need to clone the `::placeholder` pseudo element also and then it should work, however, unfortunately we actually cannot get the styles of the `::placeholder` pseudo element on every browser, even Chrome is still not supporting this ([see this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=922869)), so might need some other approach.

**Comment by thundernet8** [comment]
An alternative solution: set the value of empty inputs to match the placeholder and modify the input color style accordingly, for example, to 'gray'.
