### ISSUE TITLE
removeProperty background-color

### ISSUE THREAD

**Issue by lokomass** [bubkoo/html-to-image#385]
Hi,

I'm trying to remove only css background-color property on filter function.
This doesn't work.

Here is an example : https://codesandbox.io/s/pensive-brattain-pllp2k?file=/src/App.js

Thanks for help !

**Comment by iosiflivadaru** [comment]
Hey @lokomass, looks like there was an issue with appending that html string to the DOM. I got it where it works to be appended, but I'm not sure what else you are trying to achieve beyond that point. Hope that helps!

https://codesandbox.io/s/strange-worker-w70hh7?file=/src/App.js:668-837

**Comment by lokomass** [comment]
Thanks for your reply.
Here is my sandbox : https://codesandbox.io/s/cocky-sea-090679?file=/src/App.js
The other was a test.

**Comment by iosiflivadaru** [comment]
Your issue here is `.cloneNode(true)` if you remove that, it will work.

**Comment by lokomass** [comment]
Yes, but I only want to remove green background for the pdf exported, not in the rendered DOM.

**Comment by lokomass** [comment]
Thanks for your reply.
I need to not see any change on DOM for my users, so modify before export to pdf is not possible.
I've tried to clone in a div, not hidden, but with marginLeft -9999px for example, but it's doesn't work too.
I need to just removeProperty background, not remove completly node.
I've tried many things, but nothing works :(

**Comment by qq15725** [comment]
https://codesandbox.io/s/little-flower-giovko?file=/src/App.js

Can use the `modern-screenshot` forked library with the `onCloneNode` option ~

**Comment by lokomass** [comment]
this is exactly what I need ! thanks !!
