### ISSUE TITLE
Now there are many fonts in the project, if I want to download only one font, how to achieve?

### ISSUE THREAD

**Issue by webpig** [bubkoo/html-to-image#387]

**Comment by sirganya** [comment]
You can use embedFontCss to skip parsing the element for font rules.

```javascript
const fontCss = `@font-face {font-family: "DegularDisplayDemo-Bold.otf"; src: url("http://localhost:3000/get-font/DegularDisplayDemo-Light.otf") format("opentype"}`;

toPng(node, {
  fontEmbedCSS: fontCss,
}).then(...

```

**Comment by webpig** [comment]
> You can use embedFontCss to skip parsing the element for font rules.
> 
> ```js
> const fontCss = `@font-face {font-family: "DegularDisplayDemo-Bold.otf"; src: url("http://localhost:3000/get-font/DegularDisplayDemo-Light.otf") format("opentype"}`;
> 
> toPng(node, {
>   fontEmbedCSS: fontCss,
> }).then(...
> ```

Thanks, I tried this way before, but I have two fonts: bold and regular, and one didn't render properly.  I don't know what to do.

**Comment by sirganya** [comment]
Yes, I'm having a lot of issues with fonts not rendering. Does that method work for one font, if so what format is it in?
