### ISSUE TITLE
Full build of html-to-image 

### ISSUE THREAD

**Issue by Hareck** [bubkoo/html-to-image#41]
For a first start or for trials with html-to-image it would be great to have a full build of html-to-image at your homepage github.com/bubkoo/html-to-image, . e.g. html-to-image(.min).js . Similar to github.com/tsayen/dom-to-image, there are a dom-to-image.min.js and a dom-to-image.js available.

**Comment by nonbasketless** [comment]
I could really use this too. I'm rather clueless about anything JS (backend C++ dev here). What's the right way to do this?

**Comment by zizther** [comment]
+1
Would be good to include this, then it is also possible to include as a resource from JSDelivr https://www.jsdelivr.com/package/npm/html-to-image as another option

**Comment by zizther** [comment]
Keeping this issue alive

**Comment by bubkoo** [comment]
It's available on unpkg.com: https://unpkg.com/html-to-image@latest/dist/html-to-image.js

**Comment by darkworks** [comment]
> It's available on unpkg.com: https://unpkg.com/html-to-image@latest/dist/html-to-image.js

its giving error in browser 
`Uncaught ReferenceError: exports is not defined`

**Comment by darkworks** [comment]
> +1
> Would be good to include this, then it is also possible to include as a resource from JSDelivr https://www.jsdelivr.com/package/npm/html-to-image as another option

give error 

`Uncaught ReferenceError: exports is not defined`

**Comment by stefnotch** [comment]
Related issue https://github.com/bubkoo/html-to-image/issues/58
It might be nice to ship a minified JS file, but not sure how worthwhile this would really be.

**Comment by darkworks** [comment]
> Related issue #58
> It might be nice to ship a minified JS file, but not sure how worthwhile this would really be.

ya a lot of benefits because mostly html to image is needed on client side not server side , not sure  how people using this on server side because sending html to server side mean loss of css  , when u do this on client side u have css preserved

**Comment by romaincazier** [comment]
I was looking for a full build as well and here's how I did it:
- Clone the repo
- `npm install`
- In [tsconfig.json](https://github.com/bubkoo/html-to-image/blob/master/tsconfig.json), change line 3 to `"module": "es6"`
- In [rollup.config.js](https://github.com/bubkoo/html-to-image/blob/master/rollup.config.js), change line 12 to `format: "iife"`
- `npm run build`
- Done, you have your dist/html-to-image.js ready to be used in your front-end

**Comment by Jean-Zombie** [comment]
I did as @romaincazier did, but I had to do `npm install --force` due to dependency issues.

**Comment by ninbit** [comment]
@romaincazier and @Jean-Zombie can you please provide your built js file?

**Comment by romaincazier** [comment]
@ninbit have you tried to follow the instructions I provided ? I just tried again and had to do `npm install --force` as @Jean-Zombie suggested.

In any case here is a [build](https://gist.github.com/romaincazier/d3131e7cb57a3674fd92845aff9b7859).
