### ISSUE TITLE
Couldnt convert the Image: Cannot read properties of undefined (reading 'defaultView')

### ISSUE THREAD

**Issue by Parathantl** [bubkoo/html-to-image#410]
Summary of Issue:
I am using React and wanted to download the parsed HTML element as an Image when the button clicks. But, it doesn't do as expected.
In the console, it gives an error.

### Expected Behavior

It should download the image version of parsed HTML content

### Current Behavior

It gives error as:
TypeError: Cannot read properties of undefined (reading 'defaultView')

### Steps To Reproduce

1. Create a new React Project
2. Install the library and import as follow:
`import { toPng } from 'html-to-image';
`
3.
` 
 const onButtonClick = (htmlContent) => {
    if (htmlContent === null) {
      return;
    }

    console.log('on button click::', htmlContent); // Content consoles here...

    toPng(htmlContent, { cacheBust: true })
      .then((dataUrl) => {
        const link = document.createElement('a');
        link.download = 'my-image-name.png';
        link.href = dataUrl;
        link.click();
      })
      .catch((err) => {
        console.log(err);
      });
  };`

-  "html-to-image": "^1.11.11",
- OS: Windows 10
- Browser: Google Chrome

**Comment by hylarucoder** [comment]
@Parathantl 

wrapping your component in a div may helps


in my vue case， 

```
          <div >
            <UCard ref={elShare}


```

to

```
          <div ref={elShare}>
            <UCard

```

solved

**Comment by Parathantl** [comment]
@hylarucoder Thanks it solved to me.

**Comment by PerikalaSandeep** [comment]
in my vue,  
htmlToImage.toPng(data.html)
          .then(function (dataUrl) {
            console.log(dataUrl, 'dataUrl');
            // download(dataUrl, 'my-node.png');
          }).catch(function (error) {
            console.error('oops, something went wrong!', error);
          });;
          
i am using dynamic html code, generated form unlayer. now i am getting  
TypeError: Cannot read properties of undefined (reading 'defaultView') 

how can i resolve ?
