### ISSUE TITLE
Generates the html to image - But only the screen which we are viewing

### ISSUE THREAD

**Issue by vikash09** [bubkoo/html-to-image#43]
It's working fine but,
It's unable to generate the image of scrolling div,
Only generates the part which is visible, the other part of scrollable div get cut.
![Screen Shot 2020-03-06 at 2 38 23 PM](https://user-images.githubusercontent.com/21213817/76068970-28b82780-5fb8-11ea-81ed-3a927709f350.png)

**Comment by Kasun002** [comment]
im also facing same issue

**Comment by Sher-V** [comment]
same isuue

**Comment by mvinoba** [comment]
Any workarounds for this issue?

**Comment by anti-destin** [comment]
My workaround is essentially the following:

1. Resize the container div (e.g., set: `height: 1600px !important; width: 1600px !important;`) to prevent any overflow or scrolling. I do this by adding a special css class.
2. Generate the image.
3. Resize the container div back to the original size (e.g., by removing the special css class, etc.).

**Comment by venkateshpullaganti** [comment]
Anyone who are looking for 
- Fix the issue without resizing / can't resize 
- Still persist the nested scrolling

We can do below things if the UI is light weight
- Render complete component in a container with height & width as 0 and overflow:auto.
- All the children containers overflow visible 

`
htmltoimage.toPng(node, {
                            width: node.scrollWidth,
                            height: node.scrollHeight
                        }).then(()=>{})
`

rendering the wanted image in a container with invisible height and width. Download with its scrollheight and scrollwidth.
