### ISSUE TITLE
Unable to generate image from valid HTML - getting empty Image

### ISSUE THREAD

**Issue by manuelpoelzl** [bubkoo/html-to-image#449]
I'm unable to get any image from a valid HTMLElement.
The HTML looks fine but the `toJPG` and `toPNG` functions return an empty data url .

### Expected Behavior
The HTML should be converted to an image and the data url should get returned.
### Current Behavior
The dataUrl is `data:,` for a perfectly fine HTML
### Possible Solution
N/A
### Steps To Reproduce

1. Get an HTML string
2. Parse this string with the DOMParser class
3. Access the `documentElement`
4. console log the said element (you'll see that the HTML is perfectly fine)
5. Call the `toPng` function with the said element
6. The returned data url is `data:,`

### Your Environment

- html-to-image: 1.11.11
- OS: Windows 10 Pro 22H2
- Browser: Microsoft Edge 120.0.2210.133

**Comment by Dhan3777** [comment]
+1 @manuelpoelzl

**Comment by KhoaTheBest** [comment]
I also have same issue

**Comment by Ninamma** [comment]
Is your element a `div`? I had a similar issue when the element I was trying render was a `span`, but I saw [this comment](https://github.com/bubkoo/html-to-image/issues/222#issuecomment-1006047595) and changed the element to be a `div` and that has fixed this issue, although I don't fully understand why.

**Comment by Ninamma** [comment]
I just realised that my issue wasn't actually related to the element being `div` or `span` 🤦‍♀️ 
I think the element just needs to **not** be `display: inline` and have measurable width and height. So if I set the `span` to `display: flex` it works as well.

**Comment by PushparajGabhane** [comment]
Try adding height and width to the container where HTML is wrapped.
