### ISSUE TITLE
It will not be rendered If the style of the div tag is set to "position: absolute"

### ISSUE THREAD

**Issue by LeoMsky** [bubkoo/html-to-image#48]

**Comment by LeoMsky** [comment]
such as:
let div = document.createElement("div");
div.style.display = CSSDisplay.inlineBlock;
**div.style.position = CSSPosition.relative;**
div.style.overflow = CSSOverflow.hidden;
div.style.width = pageWidth + "px";
div.style.height = pageHeight + "px";
div.style.backgroundColor = "RGB(0,255,0)";

**Comment by abbas1994** [comment]
I can confirm I'm having this issue too.

**Comment by abbas1994** [comment]
I fixed this by adding `position: relative` to the parent

**Comment by zcqno1** [comment]
Why not use the `options.style` to override the `position:absolute` div ? You have no need to keep the position but the initial position, bringing the div into view of the svg. 
BTW, it's a little more complicated when child nodes under the div is out of view.
