### ISSUE TITLE
Looking for the single file dist

### ISSUE THREAD

**Issue by JuanAntelo** [bubkoo/html-to-image#5]
Where is it? / How do I build the project to generate it?

**Comment by pnoe** [comment]
Hi,
sorry but I did not succeed to generate a single js file to load in a browser with "script... "
Some more help to generate a dist repertory like in the dom-to-image project would be much appreciated.
Thanks.
Pierre.

**Comment by AlessandroBattistini** [comment]
I add myself to the request. 
I have some problems to install npn in a server. 
A single js file minimized would be appreciated a lot.  
Thanks and thank for your job.
