### ISSUE TITLE
Font family and font size changed in created canvas

### ISSUE THREAD

**Issue by AneriFumtiwala** [bubkoo/html-to-image#51]
Hello,

I am facing issue with fonts while converting dom into canvas using htmltoimage.toCanvas function. Generated canvas has different font family and font size which is creating in my final output. I also tried to set style object but that didn't work. 

Can you help me out with this? Really Urgent.

**Comment by MarioRozic** [comment]
I had a similar issue, what worked for me is importing fonts locally!!

**Comment by AbsentmindedInsanity** [comment]
I am also having this issue

**Comment by MrOli3000** [comment]
> I had a similar issue, what worked for me is importing fonts locally!!

How did you do this?

Im unable to get google fonts to work when generating an svg in Safari or any mobile browser.
