### ISSUE TITLE
Not all images are loading when saving image to jpeg on iOS

### ISSUE THREAD

**Issue by zizther** [bubkoo/html-to-image#52]
I have a pretty simple section I am saving as an image.
On web and Android it works fine, however on iOS it seems to include 1 of 3 images on every other download.

I have 3 images, nothing over 70kb. All assets are loaded before the save to jpeg event happens. But one of the images only shows in the saved image every other time, but the other 2 images show fine.
1 image is loaded from an external source and the other 2 are references locally.

I have tried CSS background, img tags and base64, all have the same issue.

Any ideas why this would be happening?

**Comment by de-don** [comment]
I have the same problem with google maps screenshot :(

**Comment by de-don** [comment]
I think it can be fixed by adding new optional parameter for the delay:
https://github.com/bubkoo/html-to-image/blob/f92355527abdb8f4835e96b896f21b2df7186e40/src/index.ts#L83

**Comment by zizther** [comment]
Keeping this issue alive

**Comment by Epsilon-Rashmi** [comment]
The download behaviour is not consistent on iPhone safari, especially on IOS 14+. 
Any similar issues identified? 
A quick resolution would be appreciated as we are facing this issue in our production environment and it is critical.

**Comment by zizther** [comment]
We found no workaround for this, we tried several things, such as a delay, but found that every other image being saved would not include all the images. In our instance for the production environment it ended up not being a massive issue with the client, but not sure what can be done to resolve this.

We encountered no other issues with our build setup.

**Comment by zizther** [comment]
@bubkoo Just wondering if you had any thoughts or suggestions on this issue.

**Comment by tofiqquadri** [comment]
This issue still exists.

**Comment by MrOli3000** [comment]
I have the same issue. Its occuring on iOS devices and Safari occasionally.

I can only get an image to be be included in the htmlToImage.toJpeg about 2/3 times.

**Comment by polymorpher** [comment]
Yes, I have the same issue. Can this be reopened and investigated?

**Comment by ermincelikovic** [comment]
I also have the issue

**Comment by ryntab** [comment]
Same issue here as well.

**Comment by salao-na-mao** [comment]
Same!

**Comment by MrOli3000** [comment]
I found the solution. You have to run the rendering code multiple times. It used to be 2 times for me but recently that broke. Now I need to run it 3 times for it to work on Safari and iOS.

It a very dirty work around but it works: 

toJpeg(document.getElementById(idName))
      .then(function (dataURL1) {
        var link = document.createElement("a");
        link.download = "attempt1.png";
        link.href = dataURL1;
        link.click();

        return toJpeg(document.getElementById(idName));
      })
      .then(function (dataURL2) {
        var link = document.createElement("a");
        link.download = "attempt2.png";
        link.href = dataURL2;
        link.click();

        toJpeg(document.getElementById(idName)).then((dataURL3) => {
          var link = document.createElement("a");
          link.download = "attempt3.png";
          link.href = dataURL3;
          link.click();
          resolve(dataURL3);
        });
      })
      .catch((err) => {
        reject(err);
      });

**Comment by more-ginger** [comment]
Thanks @MrOli3000, had the same issue and this work-around seems to work well on Safari and iOS.

**Comment by samwangdd** [comment]
> I found the solution. You have to run the rendering code multiple times. It used to be 2 times for me but recently that broke. Now I need to run it 3 times for it to work on Safari and iOS.
> 
> It a very dirty work around but it works:
> 
> ```
> toJpeg(document.getElementById(idName))
>       .then(function (dataURL1) {
>         var link = document.createElement("a");
>         link.download = "attempt1.png";
>         link.href = dataURL1;
>         link.click();
> 
>         return toJpeg(document.getElementById(idName));
>       })
>       .then(function (dataURL2) {
>         var link = document.createElement("a");
>         link.download = "attempt2.png";
>         link.href = dataURL2;
>         link.click();
> 
>         toJpeg(document.getElementById(idName)).then((dataURL3) => {
>           var link = document.createElement("a");
>           link.download = "attempt3.png";
>           link.href = dataURL3;
>           link.click();
>           resolve(dataURL3);
>         });
>       })
>       .catch((err) => {
>         reject(err);
>       });
> ```
> 
> Update: I got it to work by running it twice now.
> 
> The trick is, you can't return toJpeg and chain it like I did above. It has be be completely nested in the last toJpeg. Like this:
> 
> ```
> toJpeg(document.getElementById(idName))
>         .then(function (dataURL1) {
>           var link = document.createElement("a");
>           link.download = "attempt1.png";
>           link.href = dataURL1;
>           link.click();
> 
>           // You can't return toJpeg and chain this. It has be be completely nested in the last toJpeg
>           toJpeg(document.getElementById(idName)).then(function (dataURL2) {
>             var link = document.createElement("a");
>             link.download = "attempt2.png";
>             link.href = dataURL2;
>             link.click();
> 
>             resolve(dataURL2);
>           });
> ```
> 
> I also detect if a user is using mobile or safari before running this:
> 
> ```
> // Detect if user is using a Safari browser or safari mobile
> export const isSafari = () => {
>   var ua = navigator.userAgent.toLowerCase();
>   if (ua.indexOf("safari") != -1) {
>     if (ua.indexOf("chrome") > -1) {
>       return false;
>     } else {
>       return true;
>     }
>      return false;
>   }
> };
> 
> // Detect if mobile is being used
> export const isMobile = () => {
>   if (
>     /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(
>       navigator.userAgent
>     )
>   ) {
>     return true;
>   }
>   return false;
> };
> ```

Thanks, It's working for me, why did the official group not fix it 😂
