### ISSUE TITLE
TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

### ISSUE THREAD

**Issue by DavidTawil** [bubkoo/html-to-image#54]
I have a project with few charts, and I want to create a pdf (using react-pdf) with those charts as images.
I've set the id for one of the charts and tried the example code as shown in the usage section: 

```
 var node = document.getElementById("bp-graph");

    htmlToImage
      .toPng(node)
      .then(function (dataUrl) {
        console.log("inside");
        var bpImage = new Image();
        bpImage.src = dataUrl;
        document.body.appendChild(bpImage);
      })
      .catch(function (error) {
        console.error("oops, something went wrong!", error);
      });
```

but I'm getting the error in the title, any idea why, or what I need to change?

**Comment by rajanaggarwal1** [comment]
did you find the solution?

**Comment by DavidTawil** [comment]
I didn't, and actually switched to html2canvas instead.
I think they work the same, and my issue was I couldn't reach the element because it was in another component

**Comment by stefnotch** [comment]
Reproducing an issue like that from just a description is quite tricky. That's probably why you never got a response. I'd recommend whipping up a minimal project that reproduces that error and report it.
