### ISSUE TITLE
Can n't generate a screenshots with active <svg/> elements(result is empty).

### ISSUE THREAD

**Issue by GarageInc** [bubkoo/html-to-image#56]
**Summary**

Can n't generate a screenshot of page with active <svg/> elements. For example: html contains svg charts (highcharts/other). But it works good with external svg-files(added as background image for `div` elements or in `img` element) 

**Expected result**: screenshots with SVG elements.

**Really**: screenshots with empty spaces for svg elements.

Does it possible to generate a screenshots with active <svg/> elements/charts?

**Comment by ramadis** [comment]
I was able to generate a screenshot for an SVG element. **However**, it doesn't seem to be processing CSS classes for SVG elements, so if the correct display of your svg relies on css classes, that might be why you are not seeing it rendered.

**Comment by bubkoo** [comment]
@GarageInc ref #61
