### ISSUE TITLE
toSvg() undefined, current readme.md on github is idfferent from npm readme 

### ISSUE THREAD

**Issue by alicericci** [bubkoo/html-to-image#57]
Current readme.md on github is different from npm readme.md 

This doesn't work: 
```js
domtoimage.toSvg(document.getElementById('my-node'), {filter: filter})
    .then(function (dataUrl) {
        /* do something */
    }); 
```
`toSvg()` is undefined, instead the current name of the function is `toSvgDataURL()`

**Comment by m0rg0t** [comment]
![image](https://user-images.githubusercontent.com/634236/95769996-694ff000-0cc1-11eb-9385-46045127d664.png)

As i can see author of the lib rename methods in README by some reason

**Comment by bubkoo** [comment]
@alicericci both `toSvg ` and `toSvgDataURL` are exported now.
