### ISSUE TITLE
There is any way to use html-to-image without npm installer?

### ISSUE THREAD

**Issue by NurulAlomAdor** [bubkoo/html-to-image#58]
We can implement html2canvas and dom-to-image by connecting a single js file like html2canvas.js and dom-to-image.js. But I didnt find any way implement html-to-image without npm installer. Please help!

**Comment by bubkoo** [comment]
@NurulAlomAdor Use unpkg http://unpkg.com/html-to-image@latest/dist/html-to-image.js or clone this repo and then build it.

**Comment by darkworks** [comment]
> @NurulAlomAdor Use unpkg http://unpkg.com/html-to-image@latest/dist/html-to-image.js or clone this repo and then build it.

giving error in browser 

`Uncaught ReferenceError: exports is not defined`

**Comment by istoan** [comment]
I get the same error message then I'm trying to use html-to-image:

> Uncaught ReferenceError: exports is not defined

Any solutions?

**Comment by ninbit** [comment]
Hi, is there any updates to use it in browser? Or any guidelines how to convert it to JS?
