### ISSUE TITLE
PNG image rendering as blank on IOS 13 view option

### ISSUE THREAD

**Issue by Epsilon-Rashmi** [bubkoo/html-to-image#66]
### Expected Behavior

On IOS 13 iPhone devices, when clicked on download the download manager displays "view" or "Download" options, when chosen view option the PNG image preview to open.

### Current Behavior

On IOS 13 iPhone devices, when clicked on download the download manager displays "view" or "Download" options, when chosen view option the screen is bank.

### Steps To Reproduce

1. Open the application on Safari browser on IOS 13^
2. Click on download link
3. Download manager shows a popup with options "View " or "Download"
4. Click on "View" 
5. The screen is blank

<details><summary>Error Message & Stack Trace</summary><p>

### Your Environment

- html-to-image: html-to-image@0.1.1
- OS: 13+
- Browser: Safari

**Comment by MrOli3000** [comment]
This is happening to me too. My images are in the dataURL format though. The images are not included in the final image of the htmlToImage.Jpeg 33% of the time. The HTML is written to and image fine except the image is not included.

**Comment by vegetablesalad** [comment]
Same here! Using background-image with dataURL and no image on canvas on png.

**Comment by andreastepel** [comment]
Any news or solutions here? I am running into the same issue that included images (.png) are completely blank when creating a image with Safari.

**Comment by lizy0329** [comment]
> Any news or solutions here? I am running into the same issue that included images (.png) are completely blank when creating a image with Safari.

use html2canvas
