### ISSUE TITLE
import but undefined

### ISSUE THREAD

**Issue by AlexDuc** [bubkoo/html-to-image#7]
import html2Image from 'html-to-image'
console.log(html2Image)

I got undefined.
I was trying to use it with Vuejs
Please help

**Comment by Varenthein** [comment]
Use `require` if you can. I've had an exact problem and changing the code from import to `const htmlToImage = require('html-to-image')
` has worked.

**Comment by thatgriffith** [comment]
@Varenthein It solved the problem. Thanks!

**Comment by ajmal-zennify** [comment]
I also solved the problem with using require, but this issue should be resolved.

**Comment by andyrichardson** [comment]
No need to use require. The problem is that there is no default import. This needs to be added or the docs need to be updated to this:

```tsx
import * as htmlToImage from 'html-to-image';
```

**Comment by bubkoo** [comment]
@AlexDuc Readme updated: https://github.com/bubkoo/html-to-image#usage, check it again.

**Comment by andyrichardson** [comment]
@bubkoo that's awesome! Issue closed?
