### ISSUE TITLE
option.pixelRatio: 2 offsets content and doesnt scale it

### ISSUE THREAD

**Issue by maximilianMairinger** [bubkoo/html-to-image#72]
### Expected Behavior

option.pixelRatio should just increase / decrease the exported image resolution

### Current Behavior

The image width and height gets scaled up, but its content (the html) does not get scaled. Resulting in an transparent border right and bottom of the image.

### Possible Solution

I encountered this problem on a 4k monitor with scaling set to 2. The quickfix for me was to hardcode scaling to 1, to avoid the borders. I know that this does absolutely not fix the root cause, but for my usecase it was fine.

### Steps To Reproduce

Live example: https://7d26197.taskforce.maximilian.mairinger.com/

1. Click download
2. Open image
3. See empty offset

Line of code in question:
https://github.com/maximilianMairinger/taskforce/blob/7d261971812f51061d81c6eae12ef07335d4d220/app/_component/site/site.ts#L186

### Your Environment

- html-to-image: 1.3.20
- monitor: 4k, windows scaling: 2
- OS: windows
- Browser: chrome

**Comment by maximilianMairinger** [comment]
This may be an issue with shadow roots. As I had the same issue in puppeteer

**Comment by perttuim** [comment]
> @perttuim This may be an issue with shadow roots. As I had the same issue in puppeteer

Thanks for your answer. Might very well be since I'm working with Ionic which uses shadow roots extensively. Any idea on how to begin resolving this? For now I'm experimenting cloning the element off screen and setting the element dimensions to the desired image output size with pixel ratio set to 1. Not ideal but seems to work for now...

**Comment by influz** [comment]
I have the same problem. The option.pixelRatio did not work. Only canvas sizes are adjusted without including dome elements. The result is the same as doubling the with option value. We've been trying for days, and now we're doubling the dom element itself to canvas. However, it has not achieved satisfactory results.

**Comment by influz** [comment]
i sovled my problem.

"context.scale(ratio,ratio);" 

this code was removed from 0.1.1 
but this code looks important to scale canvas.

**Comment by dkrape** [comment]
I'm having the same problem. @influz's solution worked.

For further reference, I added the code `context.scale(ratio,ratio);` in the `toCanvas` function, just before `context.drawImage(image, 0, 0);`

Not sure if this is an issue with my implementation, but setting the `width` and `height`, which I would expect to set the exported image, does not appear to do anything.

**Comment by maximilianMairinger** [comment]
ping

**Comment by fpstidston** [comment]
Ping

**Comment by yuhao1118** [comment]
Hi all,
I encountered the same problem and fix it in #102. Can anybody check if it works for you as well?

**Comment by d00ML0rDz** [comment]
@yuhao1118 Just tried your fix and that looks to have resolved it for me 👍
