### ISSUE TITLE
Images in svgs won't get rendered

### ISSUE THREAD

**Issue by fgerschau** [bubkoo/html-to-image#73]
When trying to render an SVG that contains images (`<image />`), the images will be omitted.

I will add more details when I find the time to do so. Thanks for this otherwise awesome library 😊

**Comment by tilince** [comment]
@fgerschau did you find the solution?

**Comment by fgerschau** [comment]
@tilince unfortunately, I didn't. I haven't worked on that project again :sweat_smile:

**Comment by shuhankuang** [comment]
any solution? thanks.

**Comment by maurodesouza** [comment]
Hi!

I'm working on this issue already!

**Comment by toguvr** [comment]
any solution ? its happends with me to, i am rendering an image and downloading with downloadjs, the svg that i appended is ok, fonts ok, span and h1 ok, but the image dont render.

**Comment by oefeningen** [comment]
I'm facing te same problem I think.
I'm rendering an image  with variable svg files. but al the images are not rendering.

This is what it should be
![wanted](https://user-images.githubusercontent.com/29915296/111371081-3dce9880-8699-11eb-9683-5befc3ff0ebc.png)

But this is what i get:
![result](https://user-images.githubusercontent.com/29915296/111371139-5179ff00-8699-11eb-8b4a-4f2f5ddffc4f.png)

Is there an extra setting i could try??

**Comment by toguvr** [comment]
Where are you hosting your images? I saw and my problem is only with images come from other host...

**Comment by oefeningen** [comment]
They are in the same host.
They are generated like this

`
    <svg :viewBox="viewbox" :width="breedte" :height="hoogte" preserveAspectRatio="xMinYMin meet"> >
            <g>
                
                <use :xlink:href="'/statics/telsymbolen.svg#'+tekeningen[0]" :width="grootte" x="0" y="0"/>
                 ...
         </g>
    </svg>

      `
The file telsymbolen.svg contains different symbols with an id.
I'm using vuejs to determine which item to render.

**Comment by oefeningen** [comment]
I made a codesandbox to demonstrate the problem.
You can find it here: [https://codesandbox.io/s/html-to-image-test-ztf5o?file=/src/pages/Index.vue](url)

**Comment by rooby** [comment]
bump. go away bot

**Comment by gldraphael** [comment]
@bot-me help
/help
/lifecycle not-stale
/label not-stale

**Comment by jsuvanto** [comment]
@maurodesouza please submit your fix as a pull request.

**Comment by ndisisnd** [comment]
Is this still not fixed?

**Comment by nokternol** [comment]
@maurodesouza So you have created a fork and it appears to have fixed the issue. But you do not create a PR it will never be merged in..
I could clone your fix, make a fresh form and submit it myself but this seems a bit underhanded (like I would be taking credit for your work)

Could you please submit the PR as right now I have had to download your source and compile it instead of referencing the package from npm

**Comment by nokternol** [comment]
I feel I have done all I can here...
I have ported the changes into my own fork just so I can raise the PR rather than wait but the PR fails it's checks due to it trying to find a pull request on the source repo and not the target.. This is not a push request.

**Comment by deepaksardana** [comment]
Hi All, I have found a fix. Use base64 image instead of IMAGE as URL. My issue is resolved with that

**Comment by RichieRunner** [comment]
> Hi All, I have found a fix. Use base64 image instead of IMAGE as URL. My issue is resolved with that

I have tried that but got this message in the image file:
![image](https://user-images.githubusercontent.com/20289967/145652778-475bafea-3bed-49b5-8da3-dedf39ae3a14.png)

Can you please post a code snippet of what you implemented?

**Comment by xoanbeoo** [comment]
Any news on this?
