### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by linjie997** [bubkoo/html-to-image#74]
When trying to export an html node to image, I get the following erorr:
```
Error: Uncaught (in promise): ReferenceError: process is not defined
ReferenceError: process is not defined
```

### Expected Behavior
I should get the node as a image

### Current Behavior
Error

### Possible Solution
The error is in the `getPixelRatio` function:
```
const val = process && process.env ? process.env.devicePixelRatio : null
```

This may be fixed with a try catch like this:
```
let _process;
try {
   _process = process;
} catch(){
}

const val = _process && _process.env ? _process.env.devicePixelRatio : null
```

### Steps To Reproduce

<details><summary>Error Message & Stack Trace</summary><p>

```txt
Error: Uncaught (in promise): ReferenceError: process is not defined
ReferenceError: process is not defined
    at getPixelRatio (util.js:99)
    at index.js:40
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Zone.run (zone-evergreen.js:123)
    at zone-evergreen.js:857
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Zone.runTask (zone-evergreen.js:167)
    at drainMicroTaskQueue (zone-evergreen.js:569)
    at invokeTask (zone-evergreen.js:484)
    at ZoneTask.invoke (zone-evergreen.js:469)
    at resolvePromise (zone-evergreen.js:798)
    at zone-evergreen.js:705
    at rejected (tslib.es6.js:72)
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Object.onInvoke (core.js:28237)
    at ZoneDelegate.invoke (zone-evergreen.js:363)
    at Zone.run (zone-evergreen.js:123)
    at zone-evergreen.js:857
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:28225)
```

</p></details>

### Your Environment

- html-to-image: 1.3.20
- OS: Windows 10
- Browser: Chrome 87

**Comment by linjie997** [comment]
Pull request created. https://github.com/bubkoo/html-to-image/pull/75

**Comment by najmulansari** [comment]
> 👋 @linjie997
> 
> Thanks for opening your first issue here! If you're reporting a 🐞 bug, please make sure you include steps to reproduce it.
> To help make it easier for us to investigate your issue, please follow the [contributing guidelines](https://github.com/antvis/X6/blob/master/CONTRIBUTING.md).
> 
> We get a lot of issues on this repo, so please be patient and we will get back to you as soon as we can.

I fixed this by adding below code in index.html page.

`
  <script>
    var global = global || window;
    var Buffer = Buffer || [];
    var process = process || {
      env: { DEBUG: undefined },
      version: []
    };
  </script>`

**Comment by linjie997** [comment]
@najmulansari while your fix can work, it's a workaround and a fix/check should be made in the library and not by the client using it.

**Comment by linjie997** [comment]
bump

**Comment by ua-lock** [comment]
bump //
