### ISSUE TITLE
Image too small on new chrome android browsers

### ISSUE THREAD

**Issue by Mrbeyond** [bubkoo/html-to-image#76]
Summary:

  On new chrome browsers on android, when the image is downloaded, it becomes relatively too small at the top left of the image with dark blank color occupying the rest space.

Link to test:
https://medillery.com/templates/edit/two

Click on insert details button then choose format to download e.g jpg or png. 

Please I need a quick feedback on this. Thanks

**Comment by ankeshp03** [comment]
@Mrbeyond 

Please send the option **pixelRatio: 1**
When the pixelRatio is not sent, it takes the **devicePixelRatio**, which depends on the display scale.
The pixelRatio is used to set the canvas width and height.

**Comment by Mrbeyond** [comment]
Thanks @ankeshp03
