### ISSUE TITLE
Module '"node_modules/html-to-image/lib/index"' has no default export.

### ISSUE THREAD

**Issue by mikaspell** [bubkoo/html-to-image#8]
when i import lib in ts file

**Comment by jokezer** [comment]
The same thing with javascript. It's possible to import separate functions though:
```
import { toPng } from 'html-to-image';
```

**Comment by athrunsun** [comment]
Another work around is to use `import * as htmltoimage from 'html-to-image'`.

**Comment by bubkoo** [comment]
readme updated: https://github.com/bubkoo/html-to-image#usage

**Comment by bubkoo** [comment]
@mikaspell  Check `readme.md`
