### ISSUE TITLE
Scroll positions (scrollTop & scrollLeft) are lost when capturing screenshot

### ISSUE THREAD

**Issue by pbpranavk** [bubkoo/html-to-image#81]
Whenever I have a child div with scrollbars, if the user scrolls on it and takes a screenshot the scroll position is reset to initial point (to the top and to the left)

### Expected Behavior
Scroll position should be retained

### Current Behavior
Scroll position is reset to top

### Possible Solution
I don't know the solution (this is my first report in fact) but I'm willing to help and contribute if guided.

I know that the node has attributes such as scrollTop and scrollLeft, I'm not sure how but if we could check that a node is has a fixed position and apply these two properties from the original node to the copied node (while recursing), maybe we could achieve this.

### Steps To Reproduce
Codebasandbox link is [here](https://codesandbox.io/s/html-to-image-demo-x78vk?file=/src/App.js)

1. Scroll in the paragraph
2. Click on Get Screenshot button
3. Verify that the scroll position is different

<details><summary>Error Message & Stack Trace</summary><p>

```txt
No error message as such
```

</p></details>

### Additional Context

I'm trying to take a screenshot of a page with components which have overflow: auto and since the scroll position is getting reset to top in the screenshot everything is shown from the top. 

### Your Environment

- html-to-image: [e.g. 0.1.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by Sher-V** [comment]
Still opened..

**Comment by pbpranavk** [comment]
@Sher-V yes it is still open.

**Comment by martijnmichel** [comment]
I can report the same error, for the this makes the package unusable

**Comment by goforu** [comment]
same issue
