### ISSUE TITLE
Issue With Image width and Height

### ISSUE THREAD

**Issue by Mudassar755** [bubkoo/html-to-image#82]
### Expected Behavior
I want to convert a DIV element into the image in react.js. It's converting exactly that DIV, but it adds some extra width and height in the image, with **toPNG**,  **toJpeg** functions, with **toSvg** we get the exact image with same width and height but its base64-size too large, so I want to get the same result in PNG or JPEG with small size.
here is the link:
![orignnale-code](https://user-images.githubusercontent.com/42087012/104300031-c4bf9300-54e7-11eb-8ccb-02d5aacb3585.PNG)

https://codesandbox.io/s/jovial-cohen-ugwum?file=/src/App.js

it should return same result as **toSvg** in the **toPng** and **toJpeg** functions 
### Current Behavior
I want to convert a DIV element into the image in react.js. It's converting exactly that DIV, but it adds some extra width and height in the image, with **toPNG**,  **toJpeg** functions, with **toSvg** we get the exact image with same width and height but its base64-size too large, so I want to get the same result in PNG or JPEG with small size.
![toJpeg](https://user-images.githubusercontent.com/42087012/104300060-cd17ce00-54e7-11eb-91c3-696a99154967.PNG)

https://codesandbox.io/s/jovial-cohen-ugwum?file=/src/App.js

it should return same result as **toSvg** in the **toPng** and **toJpeg** functions
### Possible Solution
it should return same result as **toSvg** in the **toPng** and **toJpeg** functions

### Steps To Reproduce
* Remove extra width and height in "toPng" and "toJpeg"

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment
window10
Node: v12.16.2
React: v16.13.1

- html-to-image: [e.g. 0.1.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by ua-lock** [comment]
Can confirm this happens. Maybe replicate the node dimensions into the offscreen canvas?

**Comment by Rizzlle** [comment]
and why image is blurry ? any idea?

**Comment by Mudassar755** [comment]
It's because of image quality, by default it's 1 (100%), but I set it 0.3 (30%), to reduce the size of the base64.

**Comment by anonyhostvn** [comment]
> The generated image size is based off it's root node dimensions multiplied by the device pixel ratio. If you want to keep the generated image's size equal to your node's, add the following to your config object: `pixelRatio: 1`

Thank you for your answer.

**Comment by papakay** [comment]
@ua-lock I'm having similar issue on a mac device. When i set the pixelRation to 2, the overall image size is exactly twice the actual size of the html node. However the node image still uses pixelRation of 1. I'm on a macbook with retina screen.

Please see the output image below

`htmlToImage.toJpeg(exportNode, { backgroundColor: "#f5f7fa", pixelRatio: 2 })`

![portfolio-performance (2)](https://user-images.githubusercontent.com/5013738/105835562-40cbd780-5fcc-11eb-8620-61c3d6cb4331.jpg)

**Comment by ua-lock** [comment]
@papakay This happened to me before, but was only a concern of styling. The parent node gets stretched based off `pixelRatio`, but it's children elements might not stretch together if their dimensions (width x height) have fixed size, or it's `max-(width|height)` has a fixed value. Make sure you style it accordingly, with relative units, so it takes most of the space available.

If that doesn't solve it, there might be other workarounds, like manually doubling the node's dimensions before passing it to `htmlToImage.toJpeg()`.

Also, take note that the `getPixelRatio()` function changes went live in the latest commit, so make sure you have updated your package aswell.

**Comment by papakay** [comment]
Thank you so much @ua-lock for this useful information. I'm using version 1.3.21 which i believe has the latest update.

I've confirmed that the children element doesn't have fixed width and height. On bigger screen the size of the exported jpg is different.

Please do you have any idea on how i could double the node's dimensions?

Thanks a lot.

**Comment by andreynocap** [comment]
thank you for adding pixel ratio functionality!! 

it resolved an issue I was having: if browser gets zoomed using +/- keys, the exported image was also affected. Now with pixel ratio, export stays the size defined in width/height.
