### ISSUE TITLE
Export google map not working as expected

### ISSUE THREAD

**Issue by iccube-real** [bubkoo/html-to-image#89]
Exporting a dom with a google map inside is not working as expected.

### Current Behavior

The map is missing the markers - broken link - and the map is not correctly positioned.

Feel free to let me know if you need a 'working' example or something more.

![expected vs current](https://user-images.githubusercontent.com/8132680/105857261-6bc52400-5fea-11eb-904d-bbcdbbf7f0f5.png)

Svg version enclosed. [Map (4).zip](https://github.com/bubkoo/html-to-image/files/5873865/Map.4.zip)

Thanks for the great work.

**Comment by maxizhukov** [comment]
Same issue, any updates?
