### ISSUE TITLE
CSS involving transformX and perspective generates quarter size partially styled image on large black background

### ISSUE THREAD

**Issue by fpstidston** [bubkoo/html-to-image#90]
CSS involving transformX and perspective generates quarter size partially styled image on large black background

### Expected Behavior

<img width="318" alt="Screenshot 2021-01-28 at 16 42 19" src="https://user-images.githubusercontent.com/38984687/106169912-d2337900-6187-11eb-9980-b96a0b5f8148.png">

### Current Behavior
![image](https://user-images.githubusercontent.com/38984687/106169998-e7100c80-6187-11eb-8914-bfac4cd029df.jpeg)

### Possible Solution
include support for 3d css effects

### Steps To Reproduce
`htmlToImage.toJpeg(document.getElementById('pitch-box'), { quality: 0.95 })`

</p></details>

### Your Environment
- html-to-image: ^1.3.21
- OS: [e.g. macOS BigSur 11.1
- Browser: Safari 14.0.2

**Comment by YvesHag** [comment]
I have the same issue. can someone please help us? thanks

**Comment by andreynocap** [comment]
Have you tried setting pixelRatio flag? That may help here.

`htmlToImage.toJpeg(document.getElementById('pitch-box'), { quality: 0.95, pixelRatio: 1 })`

**Comment by Mrbeyond** [comment]
> Have you tried setting pixelRatio flag? That may help here.
> 
> `htmlToImage.toJpeg(document.getElementById('pitch-box'), { quality: 0.95, pixelRatio: 1 })`

This is the same solution that resolved it when I had the same issue. It's 100% confirmed.
