### ISSUE TITLE
Blurry when used pixelRatio 1 on mobile

### ISSUE THREAD

**Issue by Mrbeyond** [bubkoo/html-to-image#91]
### Expected Behavior
The downloaded image show have optimum quality like what you see is what you get.

### Current Behavior
 At a point the image was too small on mobile when downloaded, it didn't scale up the width and height but small image top left and blank background covers the rest. The solution suggested from a report here was to use pixelRatio to 1 explicitly and it worked but the image is now blurry when downloaded on mobile. Please I need solution to this because it's affecting production  .

### Steps To Reproduce

1. ...
2. ...
3. ...

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- html-to-image: [e.g. 0.1.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by Amigosen** [comment]
toSvg可以试试，会清晰很多

**Comment by Mrbeyond** [comment]
> toSvg可以试试，会清晰很多

I don't understand what this means, please.

**Comment by Mrbeyond** [comment]
> Try to use toSvg

It doesn't solve the problem and besides, we only want users to download png or jpg because those are the versions users are used to. And most image apps too do  not support svg.

**Comment by Mrbeyond** [comment]
Please is there an update on this particular issue, it keeps pixelating on mobile phones?

**Comment by drkPrince** [comment]
Try scaling the image size like this, 
 `const scale = 2.5    
       
  const style = {
      transform: 'scale('+scale+')',
      'transform-origin': 'center',
      width: node.offsetWidth + "px",
      height: node.offsetHeight + "px",
  }

  const param = {
     height: node.offsetHeight * scale,
     width: node.offsetWidth * scale,
     style
  }
  
  const blob = await htmlToImage.toPng(node, param)
  `
