### ISSUE TITLE
IE11 is not working...

### ISSUE THREAD

**Issue by kim1124** [bubkoo/html-to-image#94]
When running in IE11, the following error occurs.

SCRIPT1010: Expected identifier.

...
function applyStyleWidthOptions(clonedNode, options) {
  const { style } = cloneNode;
  ...
}

**Comment by robinslange** [comment]
Hey, that's expected as IE doesn't support the SVG <foreignObject> tag, thus IE is not a browser in which this library will work due to its reliance on that tag. The readme does mention this also.
